import type { CheckId, CheckMeta } from './types.js';

/**
 * The single source for everything the public site says about a check (ADR-013): its severity,
 * which score category it belongs to, which status it forces if it's a ★ check, and the English
 * copy shown on a site page and the methodology page. `site/` imports this file (via the compiled
 * `audit/dist`) and never repeats the text itself.
 *
 * Malayalam (`ml`) fields are empty strings until WP5.3 translates them -- the shape is right now
 * so that WP doesn't need to touch every entry's structure, only fill in values.
 *
 * `ref` is a citation to a specific standard section, left as `''` wherever this session isn't
 * sure enough of the exact section/number to cite it (never guessed, per the WP's own instruction).
 * A handful of checks cite the standard by name only (e.g. plain `'GIGW 3.0'`), which is accurate
 * without claiming a specific section number this session doesn't have memorised correctly.
 *
 * `statusSetting` mapping for the one case DESIGN §5.4's status table doesn't spell out
 * one-to-one against §5.3's ★ marks: `sec.https` (no HTTPS at all) is mapped to `broken` -- the
 * same "browsers won't let a citizen trust this connection" class of problem as an invalid
 * certificate, which *is* one of ADR-005's listed broken triggers. See types.ts's `StatusSetting`
 * comment for why `avail.dns`/`avail.connect`/`avail.status` map to `down` here even though that's
 * a *different* mechanism than Phase 2's own two-strike light-check `down`.
 */
export const CHECKS: Record<CheckId, CheckMeta> = {
  // ---- avail.* -- availability is a gate, not a scored category (see types.ts's Category note)
  'avail.dns': {
    category: 'availability',
    severity: 'C',
    statusSetting: 'down',
    title: { en: 'Hostname does not resolve', ml: '' },
    citizen: { en: "The site's address doesn't point anywhere right now, so nobody can reach it at all.", ml: '' },
    fix: { en: 'Check the DNS records for this domain are still correctly configured and the registration has not lapsed.', ml: '' },
    ref: '',
  },
  'avail.connect': {
    category: 'availability',
    severity: 'C',
    statusSetting: 'down',
    title: { en: 'Server did not respond', ml: '' },
    citizen: { en: 'The address resolves, but nothing answers the connection -- the server may be down or blocking requests.', ml: '' },
    fix: { en: 'Check the web server process and firewall/security-group rules are allowing normal web traffic.', ml: '' },
    ref: '',
  },
  'avail.status': {
    category: 'availability',
    severity: 'C',
    statusSetting: 'down',
    title: { en: 'Page does not load successfully', ml: '' },
    citizen: { en: 'The server responded, but with an error instead of the page, or a chain of redirects that never arrives anywhere.', ml: '' },
    fix: { en: 'Check the server logs for the error status this request returned, and fix or shorten any redirect chain.', ml: '' },
    ref: '',
  },
  'avail.redirect_offsite': {
    category: 'availability',
    severity: 'C',
    statusSetting: 'hijacked',
    title: { en: 'Site redirects to an unrelated domain', ml: '' },
    citizen: { en: "This address now sends visitors to a completely different website, not one the government runs. Don't enter any personal details there.", ml: '' },
    fix: { en: 'Reclaim the domain or its DNS/hosting, and remove the redirect; if the organisation moved permanently, tell us the new official URL.', ml: '' },
    ref: '',
  },
  'avail.parked': {
    category: 'availability',
    severity: 'C',
    statusSetting: 'hijacked',
    title: { en: 'Domain shows a "for sale" / parking page', ml: '' },
    citizen: { en: 'This address no longer hosts the real website -- it now shows a domain-registrar placeholder or a sales page.', ml: '' },
    fix: { en: 'Renew the domain registration immediately (this usually means it lapsed) and re-point it at the real site.', ml: '' },
    ref: '',
  },
  'avail.default_page': {
    category: 'availability',
    severity: 'C',
    statusSetting: 'broken',
    title: { en: 'Server\'s default page is showing, not the site', ml: '' },
    citizen: { en: 'The web server is running, but nobody has put the actual website on it yet -- you just see the software\'s own "it works" page.', ml: '' },
    fix: { en: 'Deploy the actual site content to this server and remove or replace the default landing page.', ml: '' },
    ref: '',
  },
  'avail.blank': {
    category: 'availability',
    severity: 'C',
    statusSetting: 'broken',
    title: { en: 'Page is effectively empty', ml: '' },
    citizen: { en: 'The page loads but has almost no visible text -- there is nothing here for you to read or use.', ml: '' },
    fix: { en: 'Check the CMS/build for a rendering error and restore the page\'s real content.', ml: '' },
    ref: '',
  },
  'avail.under_construction': {
    category: 'availability',
    severity: 'H',
    statusSetting: 'broken',
    title: { en: '"Under construction" page only', ml: '' },
    citizen: { en: "This site tells you it isn't ready yet and offers nothing else.", ml: '' },
    fix: { en: 'Publish the real site, or take the domain down until it is ready rather than leaving a placeholder live indefinitely.', ml: '' },
    ref: '',
  },
  'avail.ttfb': {
    category: 'availability',
    severity: 'M',
    title: { en: 'Server is slow to start responding', ml: '' },
    citizen: { en: 'The page takes an unusually long time to even start loading, before you see anything at all.', ml: '' },
    fix: { en: 'Investigate server/hosting performance (database queries, PHP-FPM/worker limits, an undersized shared-hosting plan) and add caching if the content changes rarely.', ml: '' },
    ref: '',
  },
  'avail.geo_blocked': {
    category: 'availability',
    severity: 'I',
    statusSetting: 'unverifiable',
    title: { en: 'Blocked from where we check from', ml: '' },
    citizen: { en: 'This site appears to only allow visitors from Indian internet connections, so we cannot confirm its status from here -- it may well be working fine for you.', ml: '' },
    fix: { en: 'If this block is unintentional (e.g. a CDN/WAF default), citizens abroad and NRIs may be affected too -- consider allowing normal read access.', ml: '' },
    ref: '',
  },
  'avail.flapping': {
    category: 'availability',
    severity: 'H',
    title: { en: 'Site keeps going up and down', ml: '' },
    citizen: { en: 'This site has been unreliable lately -- down for at least three of the last 28 checks over the past week.', ml: '' },
    fix: { en: 'Look for a pattern (scheduled backups, resource limits, a flaky upstream service) causing repeated short outages.', ml: '' },
    ref: '',
  },

  // ---- sec.* -- can a citizen trust the connection?
  'sec.https': {
    category: 'security',
    severity: 'C',
    statusSetting: 'broken',
    title: { en: 'Not served over HTTPS at all', ml: '' },
    citizen: { en: 'Your connection to this site is not encrypted at all -- anything you type or read can be seen or altered in transit, and modern browsers show a prominent warning.', ml: '' },
    fix: { en: 'Get a TLS certificate (NIC issues them free for .gov.in; Let\'s Encrypt for others) and serve the whole site over HTTPS.', ml: '' },
    ref: '',
  },
  'sec.http_redirect': {
    category: 'security',
    severity: 'H',
    title: { en: 'Plain http:// does not redirect to https://', ml: '' },
    citizen: { en: "If you type the address without \"https\", you land on the insecure version instead of being sent to the safe one automatically.", ml: '' },
    fix: { en: 'Add a server-level redirect from http:// to https:// for every page, not just the homepage.', ml: '' },
    ref: '',
  },
  'sec.cert_valid': {
    category: 'security',
    severity: 'C',
    statusSetting: 'broken',
    title: { en: 'HTTPS certificate is invalid or expired', ml: '' },
    citizen: { en: 'Browsers show a full-page "Your connection is not private" warning. Most people cannot get past it, so the site is effectively unreachable.', ml: '' },
    fix: { en: 'Renew the TLS certificate (NIC issues them free for .gov.in; Let\'s Encrypt for others) and turn on auto-renewal.', ml: '' },
    ref: '',
  },
  'sec.cert_expiry': {
    category: 'security',
    severity: 'H',
    title: { en: 'Certificate is about to expire', ml: '' },
    citizen: { en: 'The security certificate will stop working soon, at which point the site will show the same "not private" warning as an already-expired one.', ml: '' },
    fix: { en: 'Renew the certificate now and set up auto-renewal so this stops recurring.', ml: '' },
    ref: '',
  },
  'sec.tls_version': {
    category: 'security',
    severity: 'H',
    title: { en: 'Only an old, insecure TLS version is supported', ml: '' },
    citizen: { en: 'The site still accepts outdated encryption that modern security guidance no longer considers safe.', ml: '' },
    fix: { en: 'Disable TLS 1.0/1.1 in the web server config and require TLS 1.2 or newer.', ml: '' },
    ref: '',
  },
  'sec.hsts': {
    category: 'security',
    severity: 'M',
    title: { en: 'No HSTS header', ml: '' },
    citizen: { en: 'The site does not tell browsers to always use the secure version, so a network attacker can sometimes still trick a browser into the insecure one.', ml: '' },
    fix: { en: 'Add a Strict-Transport-Security header once HTTPS is confirmed working sitewide.', ml: '' },
    ref: 'OWASP Secure Headers',
  },
  'sec.mixed_content': {
    category: 'security',
    severity: 'H',
    title: { en: 'Secure page loads insecure content', ml: '' },
    citizen: { en: 'The page is served securely but pulls in some scripts, styles or images over an insecure connection, weakening the protection the padlock is supposed to mean.', ml: '' },
    fix: { en: 'Change every http:// resource reference on the page to https://.', ml: '' },
    ref: '',
  },
  'sec.csp': {
    category: 'security',
    severity: 'L',
    title: { en: 'No Content-Security-Policy header', ml: '' },
    citizen: { en: 'This is a technical defence-in-depth measure most visitors will never notice missing; it makes some attacks harder for the site to be tricked into if it ever has a bug.', ml: '' },
    fix: { en: 'Add a Content-Security-Policy header, starting permissive and tightening it once nothing breaks.', ml: '' },
    ref: 'OWASP Secure Headers',
  },
  'sec.xfo': {
    category: 'security',
    severity: 'M',
    title: { en: 'No clickjacking protection', ml: '' },
    citizen: { en: 'Another website could embed this page invisibly and trick you into clicking something you did not mean to.', ml: '' },
    fix: { en: 'Add an X-Frame-Options header (or a frame-ancestors directive in CSP).', ml: '' },
    ref: 'OWASP Secure Headers',
  },
  'sec.xcto': {
    category: 'security',
    severity: 'L',
    title: { en: 'No X-Content-Type-Options header', ml: '' },
    citizen: { en: 'A minor technical hardening header is missing; on its own this rarely affects you directly.', ml: '' },
    fix: { en: 'Add "X-Content-Type-Options: nosniff".', ml: '' },
    ref: 'OWASP Secure Headers',
  },
  'sec.referrer': {
    category: 'security',
    severity: 'L',
    title: { en: 'No Referrer-Policy header', ml: '' },
    citizen: { en: 'Without this, the full address of the page you came from (which can include personal details in a URL) may be leaked to other sites you click through to.', ml: '' },
    fix: { en: 'Add a Referrer-Policy header, e.g. "strict-origin-when-cross-origin".', ml: '' },
    ref: 'OWASP Secure Headers',
  },
  'sec.server_banner': {
    category: 'security',
    severity: 'L',
    title: { en: 'Server discloses exact software versions', ml: '' },
    citizen: { en: 'The server announces precisely which software and version it runs, which helps an attacker look up known weaknesses in that exact version. This alone does not put you at risk.', ml: '' },
    fix: { en: 'Configure the web server to suppress or generalise the Server/X-Powered-By headers.', ml: '' },
    ref: '',
  },
  'sec.vuln_js': {
    category: 'security',
    severity: 'H',
    title: { en: 'Uses a JavaScript library with a known vulnerability', ml: '' },
    citizen: { en: 'The page loads a script library with a publicly known security flaw, which could let an attacker interfere with the page in your browser.', ml: '' },
    fix: { en: 'Update the affected library to a version without the known vulnerability.', ml: '' },
    ref: 'OWASP A06:2021 Vulnerable and Outdated Components',
  },
  'sec.safe_browsing': {
    category: 'security',
    severity: 'C',
    statusSetting: 'hijacked',
    title: { en: 'Flagged by Google Safe Browsing', ml: '' },
    citizen: { en: 'An independent safety service has flagged this address as unsafe (phishing or malware). Do not enter any personal details here.', ml: '' },
    fix: { en: "Investigate immediately -- this usually means the site or domain was compromised. Follow Google's Safe Browsing remediation steps and request a review once fixed.", ml: '' },
    ref: '',
  },

  // ---- a11y.* -- can everyone use it? (WCAG 2.1 AA, which GIGW 3.0 mandates)
  'a11y.axe_critical': {
    category: 'accessibility',
    severity: 'H',
    title: { en: 'Critical accessibility violations', ml: '' },
    citizen: { en: 'Automated testing found serious accessibility problems that are very likely to block some visitors, such as screen-reader users, from using this page at all.', ml: '' },
    fix: { en: 'Run an accessibility scanner (e.g. axe) and fix every critical-impact violation it reports first.', ml: '' },
    ref: 'WCAG 2.1 AA',
  },
  'a11y.axe_serious': {
    category: 'accessibility',
    severity: 'M',
    title: { en: 'Serious accessibility violations', ml: '' },
    citizen: { en: 'Automated testing found accessibility problems likely to make parts of this page difficult to use for some visitors.', ml: '' },
    fix: { en: 'Fix the serious-impact violations an accessibility scanner reports.', ml: '' },
    ref: 'WCAG 2.1 AA',
  },
  'a11y.axe_moderate_minor': {
    category: 'accessibility',
    severity: 'L',
    title: { en: 'Minor accessibility issues', ml: '' },
    citizen: { en: 'Smaller accessibility issues were found; each on its own is unlikely to block anyone, but they add up.', ml: '' },
    fix: { en: 'Work through the moderate/minor findings from an accessibility scanner as time allows.', ml: '' },
    ref: 'WCAG 2.1 AA',
  },
  'a11y.lang': {
    category: 'accessibility',
    severity: 'H',
    title: { en: 'Page language is missing or wrong', ml: '' },
    citizen: { en: "A screen reader needs to know what language the page is in to pronounce it correctly -- without this, a Malayalam page read aloud in an English voice is unintelligible.", ml: '' },
    fix: { en: 'Set <html lang="ml"> (or the correct language) so it matches what the page actually contains.', ml: '' },
    ref: 'WCAG 2.1 SC 3.1.1',
  },
  'a11y.alt': {
    category: 'accessibility',
    severity: 'M',
    title: { en: 'Images missing alt text', ml: '' },
    citizen: { en: 'Someone using a screen reader hears nothing useful where an image is -- if it conveys information, that information is simply lost to them.', ml: '' },
    fix: { en: 'Add descriptive alt text to every meaningful image; use alt="" only for purely decorative ones.', ml: '' },
    ref: 'WCAG 2.1 SC 1.1.1',
  },
  'a11y.contrast': {
    category: 'accessibility',
    severity: 'M',
    title: { en: 'Text contrast is too low', ml: '' },
    citizen: { en: 'Some text is hard to read against its background, especially for visitors with low vision or in bright sunlight on a phone.', ml: '' },
    fix: { en: 'Darken text or lighten backgrounds until the contrast ratio meets WCAG AA (4.5:1 for normal text).', ml: '' },
    ref: 'WCAG 2.1 SC 1.4.3',
  },
  'a11y.headings': {
    category: 'accessibility',
    severity: 'L',
    title: { en: 'Heading structure is missing or broken', ml: '' },
    citizen: { en: 'Screen-reader users often jump between sections by heading level; a missing top-level heading or skipped levels make the page harder to navigate that way.', ml: '' },
    fix: { en: 'Add one <h1> per page and use heading levels in order without skipping.', ml: '' },
    ref: 'WCAG 2.1 SC 1.3.1',
  },
  'a11y.labels': {
    category: 'accessibility',
    severity: 'M',
    title: { en: 'Form fields without labels', ml: '' },
    citizen: { en: 'A screen reader cannot tell you what a form field is for if it has no associated label, making forms hard or impossible to fill in.', ml: '' },
    fix: { en: 'Give every form control a <label> (or aria-label) that describes what to enter.', ml: '' },
    ref: 'WCAG 2.1 SC 4.1.2',
  },
  'a11y.skip_link': {
    category: 'accessibility',
    severity: 'L',
    title: { en: 'No "skip to content" link', ml: '' },
    citizen: { en: 'Someone navigating by keyboard has to tab through the entire menu on every single page before reaching the actual content.', ml: '' },
    fix: { en: 'Add a visible-on-focus skip link at the top of the page that jumps to the main content.', ml: '' },
    ref: 'WCAG 2.1 SC 2.4.1',
  },
  'a11y.keyboard': {
    category: 'accessibility',
    severity: 'L',
    title: { en: 'Possible keyboard-navigation trap', ml: '' },
    citizen: { en: 'Some interactive elements may be unreachable or invisible to someone who navigates by keyboard alone rather than a mouse.', ml: '' },
    fix: { en: "Make sure every interactive element can be reached and clearly seen with the keyboard's Tab key alone.", ml: '' },
    ref: 'WCAG 2.1 SC 2.1.1',
  },
  'a11y.lighthouse': {
    category: 'accessibility',
    severity: 'I',
    title: { en: 'Lighthouse accessibility score', ml: '' },
    citizen: { en: "An automated overall accessibility score, shown for context -- it doesn't by itself change this site's status.", ml: '' },
    fix: { en: 'Use the specific accessibility findings above to improve this score; the number alone is not actionable.', ml: '' },
    ref: '',
  },

  // ---- perf.* -- performance & mobile
  'perf.lighthouse': {
    category: 'performance',
    severity: 'I',
    title: { en: 'Lighthouse performance score', ml: '' },
    citizen: { en: 'An automated overall speed score on a simulated slow mobile connection, shown for context.', ml: '' },
    fix: { en: 'Use the specific performance findings (large images, slow server response, layout shift) to improve this.', ml: '' },
    ref: '',
  },
  'perf.lcp': {
    category: 'performance',
    severity: 'M',
    title: { en: 'Main content is slow to appear', ml: '' },
    citizen: { en: 'The largest visible element on the page (usually a heading or image) takes a long time to show up, which feels like the page is stuck.', ml: '' },
    fix: { en: 'Optimise the largest above-the-fold image/element: compress it, size it correctly, and load it early.', ml: '' },
    ref: '',
  },
  'perf.cls': {
    category: 'performance',
    severity: 'L',
    title: { en: 'Page layout jumps around while loading', ml: '' },
    citizen: { en: 'Text and buttons shift position as the page finishes loading, which can make you tap the wrong thing.', ml: '' },
    fix: { en: 'Reserve space (width/height) for images and ads before they load, instead of letting them push content around.', ml: '' },
    ref: '',
  },
  'perf.weight': {
    category: 'performance',
    severity: 'M',
    title: { en: 'Homepage is very large to download', ml: '' },
    citizen: { en: 'The homepage transfers an unusually large amount of data, which is slow and can be expensive on a limited mobile data plan.', ml: '' },
    fix: { en: 'Compress images, remove unused scripts/styles, and enable gzip/br compression on the server.', ml: '' },
    ref: '',
  },
  'perf.viewport': {
    category: 'performance',
    severity: 'H',
    title: { en: 'Not set up for mobile screens', ml: '' },
    citizen: { en: "Most citizens will open this on a phone; without this setting the page renders as a tiny, hard-to-read desktop layout that needs constant pinch-zooming.", ml: '' },
    fix: { en: 'Add <meta name="viewport" content="width=device-width, initial-scale=1">.', ml: '' },
    ref: '',
  },
  'perf.tap_targets': {
    category: 'performance',
    severity: 'M',
    title: { en: 'Buttons/links too small or close together on mobile', ml: '' },
    citizen: { en: 'On a phone, some links or buttons are small or crowded enough that it is easy to tap the wrong one.', ml: '' },
    fix: { en: 'Increase the tap-target size and spacing for interactive elements on small screens.', ml: '' },
    ref: '',
  },
  'perf.images': {
    category: 'performance',
    severity: 'L',
    title: { en: 'Images are uncompressed or oversized', ml: '' },
    citizen: { en: 'Some images are far larger than they need to be for how they are displayed, slowing the page down for no visible benefit.', ml: '' },
    fix: { en: 'Resize images to their display dimensions and compress them (WebP/AVIF where possible).', ml: '' },
    ref: '',
  },

  // ---- content.* -- is anyone looking after it?
  'content.copyright_year': {
    category: 'content',
    severity: 'M',
    title: { en: 'Footer copyright year is old', ml: '' },
    citizen: { en: 'The copyright year in the footer is at least two years out of date, a small but visible sign nobody has touched this site recently.', ml: '' },
    fix: { en: 'Update the footer copyright year, ideally to update automatically each year.', ml: '' },
    ref: '',
  },
  'content.last_updated': {
    category: 'content',
    severity: 'H',
    title: { en: '"Last updated" date is missing or very old', ml: '' },
    citizen: { en: "There's no visible sign of when this page was last reviewed, or the date shown is over a year old -- you can't tell whether the information is still current.", ml: '' },
    fix: { en: 'Show a genuine last-reviewed/updated date on every content page, and actually keep it current.', ml: '' },
    ref: 'GIGW 3.0',
  },
  'content.stale_news': {
    category: 'content',
    severity: 'M',
    title: { en: 'News/announcements section is stale', ml: '' },
    citizen: { en: 'The newest item in the news, announcements or tenders section is over a year old, suggesting this part of the site is no longer maintained.', ml: '' },
    fix: { en: 'Post current announcements, or remove the section if it is no longer in use.', ml: '' },
    ref: '',
  },
  'content.placeholder': {
    category: 'content',
    severity: 'H',
    title: { en: 'Placeholder text left on the live site', ml: '' },
    citizen: { en: 'The page still shows template filler text ("Lorem ipsum", "sample text", "Home page description") instead of real content.', ml: '' },
    fix: { en: 'Replace every placeholder string with the real content it was standing in for.', ml: '' },
    ref: '',
  },
  'content.legacy_font': {
    category: 'content',
    severity: 'H',
    title: { en: 'Uses a non-Unicode Malayalam font', ml: '' },
    citizen: { en: 'This page uses an old-style Malayalam font (like ML-TTKarthika or ISM/Matweb) that only displays correctly if you happen to have that exact font installed -- for everyone else, the text is unreadable garbled characters.', ml: '' },
    fix: { en: 'Switch to a Unicode Malayalam font (e.g. Manjari, Noto Sans Malayalam) so the text reads correctly for everyone, with no font install required.', ml: '' },
    ref: '',
  },
  'content.obsolete_tech': {
    category: 'content',
    severity: 'M',
    title: { en: 'Uses obsolete web technology', ml: '' },
    citizen: { en: 'This page uses old technology (Flash, Java applets, <marquee>/<blink>, frames) that modern browsers no longer support at all, so part of the page may simply not work.', ml: '' },
    fix: { en: 'Replace Flash/Java-applet content and framesets with modern HTML/CSS/JS equivalents.', ml: '' },
    ref: '',
  },
  'content.best_viewed': {
    category: 'content',
    severity: 'L',
    title: { en: '"Best viewed in..." notice', ml: '' },
    citizen: { en: 'The site tells you it was only designed for one specific old browser or screen size, a sign it has not been updated for how people browse today.', ml: '' },
    fix: { en: 'Remove the notice and make the site work properly in current, common browsers and screen sizes instead.', ml: '' },
    ref: '',
  },
  'content.broken_links': {
    category: 'content',
    severity: 'H',
    title: { en: 'Broken internal links', ml: '' },
    citizen: { en: 'Some links on this site lead to pages that no longer exist or time out, which is frustrating and can hide information you were looking for.', ml: '' },
    fix: { en: 'Fix or remove each broken link; if the target page moved, add a redirect.', ml: '' },
    ref: '',
  },
  'content.broken_pdfs': {
    category: 'content',
    severity: 'M',
    title: { en: 'Linked PDFs are missing', ml: '' },
    citizen: { en: 'Some linked documents (forms, notices, reports) 404 instead of downloading, which can block you from getting an official document you need.', ml: '' },
    fix: { en: 'Re-upload the missing PDFs at their linked URLs, or update the links to where they now live.', ml: '' },
    ref: '',
  },
  'content.broken_images': {
    category: 'content',
    severity: 'L',
    title: { en: 'Broken images', ml: '' },
    citizen: { en: 'Some images fail to load, leaving broken-image icons on the page.', ml: '' },
    fix: { en: 'Fix or remove the broken image references.', ml: '' },
    ref: '',
  },
  'content.malayalam': {
    category: 'content',
    severity: 'M',
    title: { en: 'No Malayalam version available', ml: '' },
    citizen: { en: "This citizen-facing site has no Malayalam version or toggle, which shuts out anyone more comfortable reading Malayalam than English.", ml: '' },
    fix: { en: 'Add a Malayalam translation (or at minimum the key citizen-facing pages) with an easy language toggle.', ml: '' },
    ref: '',
  },
  'content.title': {
    category: 'content',
    severity: 'M',
    title: { en: 'Page title is missing or generic', ml: '' },
    citizen: { en: 'The browser tab/bookmark/search-result title just says something like "Home" or "Untitled" instead of naming the actual organisation or page.', ml: '' },
    fix: { en: 'Give every page a specific, descriptive <title>.', ml: '' },
    ref: '',
  },
  'content.meta_desc': {
    category: 'content',
    severity: 'L',
    title: { en: 'No meta description', ml: '' },
    citizen: { en: 'Search engines have nothing useful to show as a summary of this page in search results.', ml: '' },
    fix: { en: 'Add a concise <meta name="description"> summarising each page.', ml: '' },
    ref: '',
  },
  'content.favicon': {
    category: 'content',
    severity: 'L',
    title: { en: 'No favicon', ml: '' },
    citizen: { en: "The site has no small icon shown in browser tabs and bookmarks, a minor but very visible polish gap.", ml: '' },
    fix: { en: 'Add a favicon.ico (or modern equivalent) to the site.', ml: '' },
    ref: '',
  },
  'content.console_errors': {
    category: 'content',
    severity: 'L',
    title: { en: 'JavaScript errors on load', ml: '' },
    citizen: { en: "The page's own code fails partway through loading, which can silently break some feature on the page without any visible error message.", ml: '' },
    fix: { en: "Open the browser's developer console on this page and fix the reported script errors.", ml: '' },
    ref: '',
  },

  // ---- gigw.* -- does it have what GIGW 3.0 says every government site must have?
  'gigw.contact': {
    category: 'gigw',
    severity: 'H',
    title: { en: 'No "Contact Us" page', ml: '' },
    citizen: { en: 'There is no clear way to find out how to contact this office by phone, email or post.', ml: '' },
    fix: { en: 'Add a Contact Us page with a real phone number, email and postal address.', ml: '' },
    ref: 'GIGW 3.0',
  },
  'gigw.feedback': {
    category: 'gigw',
    severity: 'L',
    title: { en: 'No feedback mechanism', ml: '' },
    citizen: { en: 'There is no way to send feedback about the site itself.', ml: '' },
    fix: { en: 'Add a feedback form or a dedicated feedback email address.', ml: '' },
    ref: 'GIGW 3.0',
  },
  'gigw.sitemap': {
    category: 'gigw',
    severity: 'M',
    title: { en: 'No sitemap page', ml: '' },
    citizen: { en: "There is no page listing everything the site contains, making it harder to find something that isn't in the main menu.", ml: '' },
    fix: { en: 'Add a human-readable sitemap page linking every major section.', ml: '' },
    ref: 'GIGW 3.0',
  },
  'gigw.privacy': {
    category: 'gigw',
    severity: 'M',
    title: { en: 'No Privacy Policy', ml: '' },
    citizen: { en: "There is no statement telling you what personal information this site collects about you or what it does with it.", ml: '' },
    fix: { en: 'Publish a Privacy Policy page and link it from the footer of every page.', ml: '' },
    ref: 'GIGW 3.0',
  },
  'gigw.terms': {
    category: 'gigw',
    severity: 'L',
    title: { en: 'No Terms & Conditions / Terms of Use', ml: '' },
    citizen: { en: 'There is no page setting out the terms for using this site.', ml: '' },
    fix: { en: 'Publish a Terms of Use page.', ml: '' },
    ref: 'GIGW 3.0',
  },
  'gigw.copyright_policy': {
    category: 'gigw',
    severity: 'L',
    title: { en: 'No Copyright Policy', ml: '' },
    citizen: { en: 'There is no statement about who owns the content on this site and how it may be reused.', ml: '' },
    fix: { en: 'Publish a Copyright Policy page.', ml: '' },
    ref: 'GIGW 3.0',
  },
  'gigw.hyperlink_policy': {
    category: 'gigw',
    severity: 'L',
    title: { en: 'No Hyperlinking Policy', ml: '' },
    citizen: { en: 'There is no statement about how this site handles links to and from other websites.', ml: '' },
    fix: { en: 'Publish a Hyperlinking Policy page.', ml: '' },
    ref: 'GIGW 3.0',
  },
  'gigw.disclaimer': {
    category: 'gigw',
    severity: 'L',
    title: { en: 'No Disclaimer', ml: '' },
    citizen: { en: 'There is no disclaimer covering the accuracy or official status of the information on this site.', ml: '' },
    fix: { en: 'Publish a Disclaimer page.', ml: '' },
    ref: 'GIGW 3.0',
  },
  'gigw.accessibility_statement': {
    category: 'gigw',
    severity: 'M',
    title: { en: 'No Accessibility Statement', ml: '' },
    citizen: { en: 'There is no page explaining the site\'s accessibility commitments or how to report an accessibility problem.', ml: '' },
    fix: { en: 'Publish an Accessibility Statement with a way to report barriers.', ml: '' },
    ref: 'GIGW 3.0',
  },
  'gigw.screen_reader': {
    category: 'gigw',
    severity: 'L',
    title: { en: 'No Screen Reader Access page', ml: '' },
    citizen: { en: 'There is no page pointing screen-reader users to compatible software or usage tips for this site.', ml: '' },
    fix: { en: 'Publish a Screen Reader Access page (GIGW\'s traditional term for this).', ml: '' },
    ref: 'GIGW 3.0',
  },
  'gigw.help': {
    category: 'gigw',
    severity: 'L',
    title: { en: 'No Help page', ml: '' },
    citizen: { en: 'There is no page explaining how to use the site itself (navigation, search, common tasks).', ml: '' },
    fix: { en: 'Publish a Help page.', ml: '' },
    ref: 'GIGW 3.0',
  },
  'gigw.rti': {
    category: 'gigw',
    severity: 'H',
    title: { en: 'No RTI / Public Information Officer details', ml: '' },
    citizen: { en: "You cannot find who to contact to file a Right to Information request with this office, which is a legal right, not a courtesy.", ml: '' },
    fix: { en: "Publish the designated Public Information Officer's name, address and contact details, and how to file an RTI request.", ml: '' },
    ref: 'RTI Act 2005 s.4',
  },
  'gigw.search': {
    category: 'gigw',
    severity: 'L',
    title: { en: 'No site search', ml: '' },
    citizen: { en: 'There is no way to search this site directly; you have to browse the menu to find anything.', ml: '' },
    fix: { en: 'Add a site search facility.', ml: '' },
    ref: 'GIGW 3.0',
  },
  'gigw.ownership': {
    category: 'gigw',
    severity: 'M',
    title: { en: 'No content-ownership statement', ml: '' },
    citizen: { en: 'There is no footer statement saying which department owns this content and who built/hosts the site, making it harder to tell an official site from an impersonation.', ml: '' },
    fix: { en: 'Add a footer statement: "Content owned by <department> — Designed, developed & hosted by <agency>".', ml: '' },
    ref: 'GIGW 3.0',
  },
  'gigw.last_updated': {
    category: 'gigw',
    severity: 'M',
    title: { en: 'No last-updated date shown', ml: '' },
    citizen: { en: 'There is no visible date telling you when the site (not just one page) was last updated.', ml: '' },
    fix: { en: 'Show a site-wide last-updated date, typically in the footer.', ml: '' },
    ref: 'GIGW 3.0',
  },
  'gigw.emblem': {
    category: 'gigw',
    severity: 'I',
    title: { en: 'No state/national emblem shown', ml: '' },
    citizen: { en: 'The site does not display the state or national emblem that citizens usually look for to help recognise an official government site.', ml: '' },
    fix: { en: 'Display the appropriate emblem, used correctly per government branding guidelines.', ml: '' },
    ref: 'GIGW 3.0',
  },

  // ---- id.* -- identity & hygiene
  'id.gov_domain': {
    category: 'identity',
    severity: 'H',
    title: { en: 'Not on an official government domain', ml: '' },
    citizen: { en: "This site is on a .com/.org/.in/.net address rather than .gov.in/.nic.in/.kerala.gov.in/.ac.in/.edu.in. You cannot tell it apart from a phishing copycat by the address alone, and these domains can lapse and be bought by someone else.", ml: '' },
    fix: { en: 'Migrate to an official government domain (.gov.in/.nic.in via NIC, or .kerala.gov.in) as soon as practical.', ml: '' },
    ref: '',
  },
  'id.domain_expiry': {
    category: 'identity',
    severity: 'H',
    title: { en: 'Domain registration is about to expire', ml: '' },
    citizen: { en: 'If this domain lapses, someone else can register it and impersonate this office to the public.', ml: '' },
    fix: { en: 'Renew the domain registration now and, if possible, set it to auto-renew for several years.', ml: '' },
    ref: '',
  },
  'id.www_consistency': {
    category: 'identity',
    severity: 'L',
    title: { en: 'www and non-www versions are inconsistent', ml: '' },
    citizen: { en: 'Depending on whether you type "www." or not, you might get a different result than expected instead of one consistently redirecting to the other.', ml: '' },
    fix: { en: 'Pick one canonical form and make the other redirect to it.', ml: '' },
    ref: '',
  },
  'id.robots': {
    category: 'identity',
    severity: 'L',
    title: { en: 'No robots.txt', ml: '' },
    citizen: { en: 'This is a minor technical hygiene item about how search engines crawl the site; it rarely affects what you see directly.', ml: '' },
    fix: { en: 'Add a robots.txt that at least allows normal crawling.', ml: '' },
    ref: '',
  },
  'id.sitemap_xml': {
    category: 'identity',
    severity: 'L',
    title: { en: 'No sitemap.xml', ml: '' },
    citizen: { en: 'This helps search engines find every page on the site; without it, some pages may be harder to discover via search.', ml: '' },
    fix: { en: 'Generate and serve a sitemap.xml, and reference it from robots.txt.', ml: '' },
    ref: '',
  },
  'id.soft_404': {
    category: 'identity',
    severity: 'L',
    title: { en: 'Missing pages return "200 OK" instead of a proper error', ml: '' },
    citizen: { en: "When a page doesn't exist, the site still says everything's fine instead of telling you clearly that the page is missing, which can be confusing and hides real problems.", ml: '' },
    fix: { en: 'Return a proper 404 status (with a helpful error page) for URLs that do not exist.', ml: '' },
    ref: '',
  },
  'id.canonical': {
    category: 'identity',
    severity: 'I',
    title: { en: 'No canonical link tag', ml: '' },
    citizen: { en: 'A technical signal to search engines about which URL is the "real" one for this page is missing; it rarely affects what you see directly.', ml: '' },
    fix: { en: 'Add a <link rel="canonical"> to each page pointing at its preferred URL.', ml: '' },
    ref: '',
  },
  'id.charset_doctype': {
    category: 'identity',
    severity: 'L',
    title: { en: 'Missing UTF-8 charset or HTML5 doctype', ml: '' },
    citizen: { en: 'Without a declared UTF-8 charset, Malayalam and other non-English text can sometimes render as garbled characters in some browsers.', ml: '' },
    fix: { en: 'Add <!DOCTYPE html> and a UTF-8 charset declaration to every page.', ml: '' },
    ref: '',
  },
  'id.tech': {
    category: 'identity',
    severity: 'M',
    title: { en: 'Running old, unsupported software', ml: '' },
    citizen: { en: 'The site is built on a content-management system or platform version old enough that it likely no longer receives security updates.', ml: '' },
    fix: { en: 'Upgrade the CMS/platform to a currently-supported version.', ml: '' },
    ref: '',
  },
  'id.third_party': {
    category: 'identity',
    severity: 'I',
    title: { en: 'Loads third-party trackers', ml: '' },
    citizen: { en: 'This page loads scripts from outside companies (analytics, social-media widgets) that can track your visit, shown here for transparency rather than as a pass/fail problem.', ml: '' },
    fix: { en: 'Consider whether each third-party script is necessary, and disclose tracking in the Privacy Policy if kept.', ml: '' },
    ref: '',
  },
};
