import type { CheckId, CheckMeta } from './types.js';

/**
 * The single source for everything the public site says about a check (ADR-013): its severity,
 * which score category it belongs to, which status it forces if it's a ★ check, and the English
 * copy shown on a site page and the methodology page. `site/` imports this file (via the compiled
 * `audit/dist`) and never repeats the text itself.
 *
 * Malayalam (`ml`) fields are empty strings until WP5.3 translates them -- the shape is right now
 * so that WP doesn't need to touch every entry's structure, only fill in values.
 *
 * `ref` is a citation to a specific standard section, left as `''` wherever this session isn't
 * sure enough of the exact section/number to cite it (never guessed, per the WP's own instruction).
 * A handful of checks cite the standard by name only (e.g. plain `'GIGW 3.0'`), which is accurate
 * without claiming a specific section number this session doesn't have memorised correctly.
 *
 * `statusSetting` mapping for the one case DESIGN §5.4's status table doesn't spell out
 * one-to-one against §5.3's ★ marks: `sec.https` (no HTTPS at all) is mapped to `broken` -- the
 * same "browsers won't let a citizen trust this connection" class of problem as an invalid
 * certificate, which *is* one of ADR-005's listed broken triggers. See types.ts's `StatusSetting`
 * comment for why `avail.dns`/`avail.connect`/`avail.status` map to `down` here even though that's
 * a *different* mechanism than Phase 2's own two-strike light-check `down`.
 */
export const CHECKS: Record<CheckId, CheckMeta> = {
  // ---- avail.* -- availability is a gate, not a scored category (see types.ts's Category note)
  'avail.dns': {
    category: 'availability',
    severity: 'C',
    statusSetting: 'down',
    title: { en: 'Hostname does not resolve', ml: 'വെബ്സൈറ്റ് വിലാസം (DNS) കണ്ടെത്താനാകുന്നില്ല' },
    citizen: { en: "The site's address doesn't point anywhere right now, so nobody can reach it at all.", ml: 'ഈ വെബ്സൈറ്റിന്റെ വിലാസം ഇപ്പോൾ ഒരിടത്തേക്കും വഴി കാണിക്കുന്നില്ല, അതിനാൽ ആർക്കും ഈ സൈറ്റിൽ എത്തിച്ചേരാൻ കഴിയില്ല.' },
    fix: { en: 'Check the DNS records for this domain are still correctly configured and the registration has not lapsed.', ml: 'ഈ ഡൊമെയ്‌നിന്റെ DNS രേഖകൾ ശരിയായി ക്രമീകരിച്ചിട്ടുണ്ടോ എന്നും ഡൊമെയ്ൻ രജിസ്ട്രേഷൻ കാലഹരണപ്പെട്ടിട്ടില്ലെന്നും പരിശോധിക്കുക.' },
    ref: '',
  },
  'avail.connect': {
    category: 'availability',
    severity: 'C',
    statusSetting: 'down',
    title: { en: 'Server did not respond', ml: 'സെർവർ പ്രതികരിച്ചില്ല' },
    citizen: { en: 'The address resolves, but nothing answers the connection -- the server may be down or blocking requests.', ml: 'വിലാസം കണ്ടെത്താനായെങ്കിലും, കണക്ഷന് ആരും മറുപടി നൽകുന്നില്ല -- സെർവർ പ്രവർത്തനരഹിതമായിരിക്കാം, അല്ലെങ്കിൽ അഭ്യർത്ഥനകൾ തടയുന്നുണ്ടാകാം.' },
    fix: { en: 'Check the web server process and firewall/security-group rules are allowing normal web traffic.', ml: 'വെബ് സെർവർ പ്രോസസും ഫയർവാൾ/സെക്യൂരിറ്റി-ഗ്രൂപ്പ് നിയമങ്ങളും സാധാരണ വെബ് ട്രാഫിക് അനുവദിക്കുന്നുണ്ടെന്ന് പരിശോധിക്കുക.' },
    ref: '',
  },
  'avail.status': {
    category: 'availability',
    severity: 'C',
    statusSetting: 'down',
    title: { en: 'Page does not load successfully', ml: 'പേജ് ശരിയായി ലോഡ് ആകുന്നില്ല' },
    citizen: { en: 'The server responded, but with an error instead of the page, or a chain of redirects that never arrives anywhere.', ml: 'സെർവർ പ്രതികരിച്ചെങ്കിലും, പേജിന് പകരം ഒരു എറർ കാണിക്കുകയോ, ഒരിടത്തും എത്താത്ത റീഡയറക്ടുകളുടെ ഒരു ശൃംഖലയിലേക്ക് പോകുകയോ ചെയ്യുന്നു.' },
    fix: { en: 'Check the server logs for the error status this request returned, and fix or shorten any redirect chain.', ml: 'ഈ അഭ്യർത്ഥന നൽകിയ എറർ സ്റ്റാറ്റസിനായി സെർവർ ലോഗുകൾ പരിശോധിക്കുകയും, ഏതെങ്കിലും റീഡയറക്ട് ശൃംഖല ശരിയാക്കുകയോ ചെറുതാക്കുകയോ ചെയ്യുക.' },
    ref: '',
  },
  'avail.redirect_offsite': {
    category: 'availability',
    severity: 'C',
    statusSetting: 'hijacked',
    title: { en: 'Site redirects to an unrelated domain', ml: 'സൈറ്റ് ബന്ധമില്ലാത്ത ഒരു ഡൊമെയ്നിലേക്ക് റീഡയറക്ട് ചെയ്യുന്നു' },
    citizen: { en: "This address now sends visitors to a completely different website, not one the government runs. Don't enter any personal details there.", ml: 'ഈ വിലാസം ഇപ്പോൾ സന്ദർശകരെ പൂർണ്ണമായും വ്യത്യസ്തമായ ഒരു വെബ്സൈറ്റിലേക്ക് അയക്കുന്നു, സർക്കാർ നടത്തുന്ന ഒന്നല്ല ഇത്. അവിടെ നിങ്ങളുടെ വ്യക്തിഗത വിവരങ്ങളൊന്നും നൽകരുത്.' },
    fix: { en: 'Reclaim the domain or its DNS/hosting, and remove the redirect; if the organisation moved permanently, tell us the new official URL.', ml: 'ഡൊമെയ്നോ അതിന്റെ DNS/ഹോസ്റ്റിംഗോ തിരിച്ചുപിടിച്ച്, റീഡയറക്ട് നീക്കം ചെയ്യുക; സ്ഥാപനം സ്ഥിരമായി മാറിയതാണെങ്കിൽ, പുതിയ ഔദ്യോഗിക URL ഞങ്ങളെ അറിയിക്കുക.' },
    ref: '',
  },
  'avail.parked': {
    category: 'availability',
    severity: 'C',
    statusSetting: 'hijacked',
    title: { en: 'Domain shows a "for sale" / parking page', ml: 'ഡൊമെയ്നിൽ "വിൽപ്പനയ്ക്ക്" / പാർക്കിംഗ് പേജ് കാണിക്കുന്നു' },
    citizen: { en: 'This address no longer hosts the real website -- it now shows a domain-registrar placeholder or a sales page.', ml: 'ഈ വിലാസത്തിൽ ഇനി യഥാർത്ഥ വെബ്സൈറ്റ് ഇല്ല -- ഇപ്പോൾ ഇത് ഒരു ഡൊമെയ്ൻ-രജിസ്ട്രാർ പ്ലേസ്ഹോൾഡറോ വിൽപ്പന പേജോ കാണിക്കുന്നു.' },
    fix: { en: 'Renew the domain registration immediately (this usually means it lapsed) and re-point it at the real site.', ml: 'ഡൊമെയ്ൻ രജിസ്ട്രേഷൻ ഉടൻ പുതുക്കുക (സാധാരണയായി ഇത് കാലഹരണപ്പെട്ടതാണ് അർത്ഥമാക്കുന്നത്) കൂടാതെ യഥാർത്ഥ സൈറ്റിലേക്ക് വീണ്ടും പോയിന്റ് ചെയ്യുക.' },
    ref: '',
  },
  'avail.default_page': {
    category: 'availability',
    severity: 'C',
    statusSetting: 'broken',
    title: { en: 'Server\'s default page is showing, not the site', ml: 'സെർവറിന്റെ ഡിഫോൾട്ട് പേജാണ് കാണിക്കുന്നത്, സൈറ്റല്ല' },
    citizen: { en: 'The web server is running, but nobody has put the actual website on it yet -- you just see the software\'s own "it works" page.', ml: 'വെബ് സെർവർ പ്രവർത്തിക്കുന്നുണ്ട്, പക്ഷേ ആരും ഇതുവരെ യഥാർത്ഥ വെബ്സൈറ്റ് അതിൽ സ്ഥാപിച്ചിട്ടില്ല -- സോഫ്റ്റ്‌വെയറിന്റെ സ്വന്തം "it works" പേജ് മാത്രമാണ് നിങ്ങൾ കാണുന്നത്.' },
    fix: { en: 'Deploy the actual site content to this server and remove or replace the default landing page.', ml: 'യഥാർത്ഥ സൈറ്റ് ഉള്ളടക്കം ഈ സെർവറിൽ വിന്യസിക്കുകയും, ഡിഫോൾട്ട് ലാൻഡിംഗ് പേജ് നീക്കം ചെയ്യുകയോ മാറ്റിസ്ഥാപിക്കുകയോ ചെയ്യുക.' },
    ref: '',
  },
  'avail.blank': {
    category: 'availability',
    severity: 'C',
    statusSetting: 'broken',
    title: { en: 'Page is effectively empty', ml: 'പേജ് ഫലത്തിൽ ശൂന്യമാണ്' },
    citizen: { en: 'The page loads but has almost no visible text -- there is nothing here for you to read or use.', ml: 'പേജ് ലോഡ് ആകുന്നുണ്ട്, പക്ഷേ ദൃശ്യമായ ടെക്സ്റ്റ് ഏതാണ്ട് ഒന്നുമില്ല -- നിങ്ങൾക്ക് വായിക്കാനോ ഉപയോഗിക്കാനോ ഇവിടെ ഒന്നുമില്ല.' },
    fix: { en: 'Check the CMS/build for a rendering error and restore the page\'s real content.', ml: 'CMS/ബിൽഡിൽ ഒരു റെൻഡറിംഗ് പിശക് ഉണ്ടോ എന്ന് പരിശോധിച്ച്, പേജിന്റെ യഥാർത്ഥ ഉള്ളടക്കം പുനഃസ്ഥാപിക്കുക.' },
    ref: '',
  },
  'avail.under_construction': {
    category: 'availability',
    severity: 'H',
    statusSetting: 'broken',
    title: { en: '"Under construction" page only', ml: '"നിർമ്മാണത്തിലാണ്" (Under construction) പേജ് മാത്രം' },
    citizen: { en: "This site tells you it isn't ready yet and offers nothing else.", ml: 'ഈ സൈറ്റ് ഇത് ഇനിയും തയ്യാറായിട്ടില്ലെന്ന് പറയുന്നു, മറ്റൊന്നും വാഗ്ദാനം ചെയ്യുന്നില്ല.' },
    fix: { en: 'Publish the real site, or take the domain down until it is ready rather than leaving a placeholder live indefinitely.', ml: 'യഥാർത്ഥ സൈറ്റ് പ്രസിദ്ധീകരിക്കുക, അല്ലെങ്കിൽ തയ്യാറാകുന്നതുവരെ ഡൊമെയ്ൻ എടുത്തുകളയുക -- അനിശ്ചിതമായി ഒരു പ്ലേസ്ഹോൾഡർ ലൈവായി നിലനിർത്തരുത്.' },
    ref: '',
  },
  'avail.ttfb': {
    category: 'availability',
    severity: 'M',
    title: { en: 'Server is slow to start responding', ml: 'സെർവർ പ്രതികരിക്കാൻ തുടങ്ങാൻ വൈകുന്നു' },
    citizen: { en: 'The page takes an unusually long time to even start loading, before you see anything at all.', ml: 'നിങ്ങൾ എന്തെങ്കിലും കാണുന്നതിന് മുൻപ് തന്നെ, പേജ് ലോഡ് ആകാൻ തുടങ്ങാൻ അസാധാരണമാം വിധം സമയമെടുക്കുന്നു.' },
    fix: { en: 'Investigate server/hosting performance (database queries, PHP-FPM/worker limits, an undersized shared-hosting plan) and add caching if the content changes rarely.', ml: 'സെർവർ/ഹോസ്റ്റിംഗ് പെർഫോമൻസ് അന്വേഷിക്കുക (ഡാറ്റാബേസ് ക്വറികൾ, PHP-FPM/വർക്കർ പരിധികൾ, ചെറിയ ഷെയേർഡ്-ഹോസ്റ്റിംഗ് പ്ലാൻ) കൂടാതെ ഉള്ളടക്കം അപൂർവ്വമായി മാത്രം മാറുകയാണെങ്കിൽ കാഷിംഗ് ചേർക്കുക.' },
    ref: '',
  },
  'avail.geo_blocked': {
    category: 'availability',
    severity: 'I',
    statusSetting: 'unverifiable',
    title: { en: 'Blocked from where we check from', ml: 'ഞങ്ങൾ പരിശോധിക്കുന്ന സ്ഥലത്തുനിന്ന് തടയപ്പെട്ടിരിക്കുന്നു' },
    citizen: { en: 'This site appears to only allow visitors from Indian internet connections, so we cannot confirm its status from here -- it may well be working fine for you.', ml: 'ഈ സൈറ്റ് ഇന്ത്യൻ ഇന്റർനെറ്റ് കണക്ഷനുകളിൽ നിന്നുള്ള സന്ദർശകരെ മാത്രമേ അനുവദിക്കുന്നുള്ളൂ എന്ന് തോന്നുന്നു, അതിനാൽ ഇവിടെനിന്ന് അതിന്റെ സ്ഥിതി സ്ഥിരീകരിക്കാൻ ഞങ്ങൾക്ക് കഴിയില്ല -- നിങ്ങൾക്ക് ഇത് നന്നായി പ്രവർത്തിക്കുന്നുണ്ടാകാം.' },
    fix: { en: 'If this block is unintentional (e.g. a CDN/WAF default), citizens abroad and NRIs may be affected too -- consider allowing normal read access.', ml: 'ഈ തടയൽ ഉദ്ദേശിച്ചതല്ലെങ്കിൽ (ഉദാ: ഒരു CDN/WAF ഡിഫോൾട്ട്), വിദേശത്തുള്ള പൗരന്മാരെയും NRI-കളെയും ഇത് ബാധിച്ചേക്കാം -- സാധാരണ വായന ആക്സസ് അനുവദിക്കുന്നത് പരിഗണിക്കുക.' },
    ref: '',
  },
  'avail.flapping': {
    category: 'availability',
    severity: 'H',
    title: { en: 'Site keeps going up and down', ml: 'സൈറ്റ് വീണ്ടും വീണ്ടും പ്രവർത്തനരഹിതമാകുന്നു' },
    citizen: { en: 'This site has been unreliable lately -- down for at least three of the last 28 checks over the past week.', ml: 'ഈ സൈറ്റ് അടുത്തിടെ വിശ്വസനീയമല്ല -- കഴിഞ്ഞ ആഴ്ചയിലെ 28 പരിശോധനകളിൽ ചുരുങ്ങിയത് മൂന്നിലെങ്കിലും ഇത് പ്രവർത്തനരഹിതമായിരുന്നു.' },
    fix: { en: 'Look for a pattern (scheduled backups, resource limits, a flaky upstream service) causing repeated short outages.', ml: 'ആവർത്തിച്ചുള്ള ചെറിയ തടസ്സങ്ങൾക്ക് കാരണമാകുന്ന ഒരു പാറ്റേൺ (ഷെഡ്യൂൾ ചെയ്ത ബാക്കപ്പുകൾ, റിസോഴ്സ് പരിധികൾ, അസ്ഥിരമായ ഒരു അപ്സ്ട്രീം സേവനം) പരിശോധിക്കുക.' },
    ref: '',
  },

  // ---- sec.* -- can a citizen trust the connection?
  'sec.https': {
    category: 'security',
    severity: 'C',
    statusSetting: 'broken',
    title: { en: 'Not served over HTTPS at all', ml: 'HTTPS ഉപയോഗിച്ച് സേവനം നൽകുന്നില്ല' },
    citizen: { en: 'Your connection to this site is not encrypted at all -- anything you type or read can be seen or altered in transit, and modern browsers show a prominent warning.', ml: 'നിങ്ങളുടെ കണക്ഷൻ ഈ സൈറ്റുമായി ഒട്ടും എൻക്രിപ്റ്റ് ചെയ്തിട്ടില്ല -- നിങ്ങൾ ടൈപ്പ് ചെയ്യുന്നതോ വായിക്കുന്നതോ ആയ എന്തും വഴിയിൽ കാണാനോ മാറ്റം വരുത്താനോ കഴിയും, ആധുനിക ബ്രൗസറുകൾ ഇതിന് വ്യക്തമായ മുന്നറിയിപ്പ് കാണിക്കും.' },
    fix: { en: 'Get a TLS certificate (NIC issues them free for .gov.in; Let\'s Encrypt for others) and serve the whole site over HTTPS.', ml: 'ഒരു TLS സർട്ടിഫിക്കറ്റ് സംഘടിപ്പിക്കുക (.gov.in-നായി NIC സൗജന്യമായി നൽകുന്നു; മറ്റുള്ളവർക്ക് Let\'s Encrypt ഉപയോഗിക്കാം) കൂടാതെ മുഴുവൻ സൈറ്റും HTTPS വഴി സേവനം നൽകുക.' },
    ref: '',
  },
  'sec.http_redirect': {
    category: 'security',
    severity: 'H',
    title: { en: 'Plain http:// does not redirect to https://', ml: 'http:// വിലാസം https:// ലേക്ക് റീഡയറക്ട് ചെയ്യുന്നില്ല' },
    citizen: { en: "If you type the address without \"https\", you land on the insecure version instead of being sent to the safe one automatically.", ml: 'https ഇല്ലാതെ വിലാസം ടൈപ്പ് ചെയ്താൽ, സുരക്ഷിതമായ പതിപ്പിലേക്ക് സ്വയമേവ അയക്കപ്പെടുന്നതിന് പകരം നിങ്ങൾ അസുരക്ഷിതമായ പതിപ്പിൽ എത്തുന്നു.' },
    fix: { en: 'Add a server-level redirect from http:// to https:// for every page, not just the homepage.', ml: 'ഹോംപേജിൽ മാത്രമല്ല, എല്ലാ പേജിനും http:// ൽ നിന്ന് https:// ലേക്ക് സെർവർ-തല റീഡയറക്ട് ചേർക്കുക.' },
    ref: '',
  },
  'sec.cert_valid': {
    category: 'security',
    severity: 'C',
    statusSetting: 'broken',
    title: { en: 'HTTPS certificate is invalid or expired', ml: 'HTTPS സർട്ടിഫിക്കറ്റ് അസാധുവാണ് അല്ലെങ്കിൽ കാലഹരണപ്പെട്ടു' },
    citizen: { en: 'Browsers show a full-page "Your connection is not private" warning. Most people cannot get past it, so the site is effectively unreachable.', ml: '"നിങ്ങളുടെ കണക്ഷൻ സ്വകാര്യമല്ല" എന്ന മുന്നറിയിപ്പ് ബ്രൗസറുകൾ മുഴുവൻ സ്ക്രീനിലും കാണിക്കും. മിക്കവർക്കും ഇത് മറികടക്കാൻ കഴിയില്ല, അതിനാൽ പ്രായോഗികമായി ഈ സൈറ്റ് ഉപയോഗിക്കാൻ കഴിയാതാകും.' },
    fix: { en: 'Renew the TLS certificate (NIC issues them free for .gov.in; Let\'s Encrypt for others) and turn on auto-renewal.', ml: 'TLS സർട്ടിഫിക്കറ്റ് പുതുക്കുക (.gov.in-നായി NIC സൗജന്യമായി നൽകുന്നു; മറ്റുള്ളവർക്ക് Let\'s Encrypt ഉപയോഗിക്കാം) കൂടാതെ ഓട്ടോ-റിന്യൂവൽ ഓണാക്കുക.' },
    ref: '',
  },
  'sec.cert_expiry': {
    category: 'security',
    severity: 'H',
    title: { en: 'Certificate is about to expire', ml: 'സർട്ടിഫിക്കറ്റ് കാലഹരണപ്പെടാൻ പോകുന്നു' },
    citizen: { en: 'The security certificate will stop working soon, at which point the site will show the same "not private" warning as an already-expired one.', ml: 'സുരക്ഷാ സർട്ടിഫിക്കറ്റ് ഉടൻ പ്രവർത്തിക്കുന്നത് നിർത്തും, അപ്പോൾ കാലഹരണപ്പെട്ട ഒന്നിന്റെ അതേ "സ്വകാര്യമല്ല" മുന്നറിയിപ്പ് സൈറ്റ് കാണിക്കും.' },
    fix: { en: 'Renew the certificate now and set up auto-renewal so this stops recurring.', ml: 'സർട്ടിഫിക്കറ്റ് ഇപ്പോൾ പുതുക്കി, ഇത് ആവർത്തിക്കാതിരിക്കാൻ ഓട്ടോ-റിന്യൂവൽ സെറ്റ് ചെയ്യുക.' },
    ref: '',
  },
  'sec.tls_version': {
    category: 'security',
    severity: 'H',
    title: { en: 'Only an old, insecure TLS version is supported', ml: 'പഴയതും അസുരക്ഷിതവുമായ TLS പതിപ്പ് മാത്രമേ പിന്തുണയ്ക്കുന്നുള്ളൂ' },
    citizen: { en: 'The site still accepts outdated encryption that modern security guidance no longer considers safe.', ml: 'ആധുനിക സുരക്ഷാ മാർഗ്ഗനിർദ്ദേശങ്ങൾ ഇനി സുരക്ഷിതമായി കണക്കാക്കാത്ത കാലഹരണപ്പെട്ട എൻക്രിപ്ഷൻ ഈ സൈറ്റ് ഇപ്പോഴും അനുവദിക്കുന്നു.' },
    fix: { en: 'Disable TLS 1.0/1.1 in the web server config and require TLS 1.2 or newer.', ml: 'വെബ് സെർവർ കോൺഫിഗിൽ TLS 1.0/1.1 പ്രവർത്തനരഹിതമാക്കി, TLS 1.2 അല്ലെങ്കിൽ പുതിയത് നിർബന്ധമാക്കുക.' },
    ref: '',
  },
  'sec.hsts': {
    category: 'security',
    severity: 'M',
    title: { en: 'No HSTS header', ml: 'HSTS ഹെഡർ ഇല്ല' },
    citizen: { en: 'The site does not tell browsers to always use the secure version, so a network attacker can sometimes still trick a browser into the insecure one.', ml: 'എപ്പോഴും സുരക്ഷിത പതിപ്പ് ഉപയോഗിക്കാൻ ബ്രൗസറുകളോട് ഈ സൈറ്റ് പറയുന്നില്ല, അതിനാൽ ഒരു നെറ്റ്‌വർക്ക് ആക്രമണകാരിക്ക് ചിലപ്പോഴൊക്കെ ബ്രൗസറിനെ അസുരക്ഷിത പതിപ്പിലേക്ക് കബളിപ്പിക്കാൻ കഴിഞ്ഞേക്കും.' },
    fix: { en: 'Add a Strict-Transport-Security header once HTTPS is confirmed working sitewide.', ml: 'HTTPS സൈറ്റ് മുഴുവനും പ്രവർത്തിക്കുന്നുവെന്ന് സ്ഥിരീകരിച്ചാൽ ഒരു Strict-Transport-Security ഹെഡർ ചേർക്കുക.' },
    ref: 'OWASP Secure Headers',
  },
  'sec.mixed_content': {
    category: 'security',
    severity: 'H',
    title: { en: 'Secure page loads insecure content', ml: 'സുരക്ഷിത പേജ് അസുരക്ഷിത ഉള്ളടക്കം ലോഡ് ചെയ്യുന്നു' },
    citizen: { en: 'The page is served securely but pulls in some scripts, styles or images over an insecure connection, weakening the protection the padlock is supposed to mean.', ml: 'പേജ് സുരക്ഷിതമായി തന്നെയാണ് നൽകുന്നതെങ്കിലും, ചില സ്ക്രിപ്റ്റുകളോ സ്റ്റൈലുകളോ ചിത്രങ്ങളോ അസുരക്ഷിതമായ കണക്ഷൻ വഴി കൊണ്ടുവരുന്നു, ഇത് പാഡ്ലോക്ക് അർത്ഥമാക്കുന്ന സംരക്ഷണത്തെ ദുർബലപ്പെടുത്തുന്നു.' },
    fix: { en: 'Change every http:// resource reference on the page to https://.', ml: 'പേജിലെ എല്ലാ http:// റിസോഴ്സ് റഫറൻസുകളും https:// ആയി മാറ്റുക.' },
    ref: '',
  },
  'sec.csp': {
    category: 'security',
    severity: 'L',
    title: { en: 'No Content-Security-Policy header', ml: 'Content-Security-Policy ഹെഡർ ഇല്ല' },
    citizen: { en: 'This is a technical defence-in-depth measure most visitors will never notice missing; it makes some attacks harder for the site to be tricked into if it ever has a bug.', ml: 'ഇത് ഒരു സാങ്കേതിക അധിക-സുരക്ഷാ നടപടിയാണ്, മിക്ക സന്ദർശകരും ഇത് ഇല്ലെന്ന് ഒരിക്കലും ശ്രദ്ധിക്കില്ല; സൈറ്റിന് എപ്പോഴെങ്കിലും ഒരു ബഗ് ഉണ്ടായാൽ ചില ആക്രമണങ്ങളിലേക്ക് കബളിപ്പിക്കപ്പെടുന്നത് ഇത് കൂടുതൽ ബുദ്ധിമുട്ടാക്കുന്നു.' },
    fix: { en: 'Add a Content-Security-Policy header, starting permissive and tightening it once nothing breaks.', ml: 'ഒരു Content-Security-Policy ഹെഡർ ചേർക്കുക, അയഞ്ഞ രീതിയിൽ തുടങ്ങി ഒന്നും തകരാറാകുന്നില്ലെന്ന് ഉറപ്പായാൽ കർശനമാക്കുക.' },
    ref: 'OWASP Secure Headers',
  },
  'sec.xfo': {
    category: 'security',
    severity: 'M',
    title: { en: 'No clickjacking protection', ml: 'ക്ലിക്ക്ജാക്കിംഗ് (clickjacking) പരിരക്ഷ ഇല്ല' },
    citizen: { en: 'Another website could embed this page invisibly and trick you into clicking something you did not mean to.', ml: 'മറ്റൊരു വെബ്സൈറ്റിന് ഈ പേജ് അദൃശ്യമായി ഉൾപ്പെടുത്തി, നിങ്ങൾ ഉദ്ദേശിക്കാത്ത എന്തെങ്കിലും ക്ലിക്ക് ചെയ്യാൻ നിങ്ങളെ കബളിപ്പിക്കാൻ കഴിയും.' },
    fix: { en: 'Add an X-Frame-Options header (or a frame-ancestors directive in CSP).', ml: 'ഒരു X-Frame-Options ഹെഡർ (അല്ലെങ്കിൽ CSP-യിൽ ഒരു frame-ancestors ഡയറക്റ്റീവ്) ചേർക്കുക.' },
    ref: 'OWASP Secure Headers',
  },
  'sec.xcto': {
    category: 'security',
    severity: 'L',
    title: { en: 'No X-Content-Type-Options header', ml: 'X-Content-Type-Options ഹെഡർ ഇല്ല' },
    citizen: { en: 'A minor technical hardening header is missing; on its own this rarely affects you directly.', ml: 'ഒരു ചെറിയ സാങ്കേതിക സുരക്ഷാ ഹെഡർ ഇല്ല; ഇത് മാത്രമായി അപൂർവ്വമായേ നിങ്ങളെ നേരിട്ട് ബാധിക്കൂ.' },
    fix: { en: 'Add "X-Content-Type-Options: nosniff".', ml: 'X-Content-Type-Options: nosniff ചേർക്കുക.' },
    ref: 'OWASP Secure Headers',
  },
  'sec.referrer': {
    category: 'security',
    severity: 'L',
    title: { en: 'No Referrer-Policy header', ml: 'Referrer-Policy ഹെഡർ ഇല്ല' },
    citizen: { en: 'Without this, the full address of the page you came from (which can include personal details in a URL) may be leaked to other sites you click through to.', ml: 'ഇത് ഇല്ലാതെ, നിങ്ങൾ വന്ന പേജിന്റെ പൂർണ്ണ വിലാസം (URL-ൽ വ്യക്തിഗത വിവരങ്ങൾ ഉൾപ്പെട്ടേക്കാം) നിങ്ങൾ ക്ലിക്ക് ചെയ്ത് പോകുന്ന മറ്റ് സൈറ്റുകളിലേക്ക് ചോർന്നേക്കാം.' },
    fix: { en: 'Add a Referrer-Policy header, e.g. "strict-origin-when-cross-origin".', ml: 'ഒരു Referrer-Policy ഹെഡർ ചേർക്കുക, ഉദാ: strict-origin-when-cross-origin.' },
    ref: 'OWASP Secure Headers',
  },
  'sec.server_banner': {
    category: 'security',
    severity: 'L',
    title: { en: 'Server discloses exact software versions', ml: 'സെർവർ കൃത്യമായ സോഫ്റ്റ്‌വെയർ പതിപ്പുകൾ വെളിപ്പെടുത്തുന്നു' },
    citizen: { en: 'The server announces precisely which software and version it runs, which helps an attacker look up known weaknesses in that exact version. This alone does not put you at risk.', ml: 'ഏത് സോഫ്റ്റ്‌വെയറും പതിപ്പുമാണ് പ്രവർത്തിക്കുന്നതെന്ന് സെർവർ കൃത്യമായി അറിയിക്കുന്നു, ഇത് ആ കൃത്യമായ പതിപ്പിലെ അറിയപ്പെടുന്ന ദൗർബല്യങ്ങൾ കണ്ടെത്താൻ ഒരു ആക്രമണകാരിയെ സഹായിക്കും. ഇത് മാത്രം നിങ്ങളെ അപകടത്തിലാക്കുന്നില്ല.' },
    fix: { en: 'Configure the web server to suppress or generalise the Server/X-Powered-By headers.', ml: 'Server/X-Powered-By ഹെഡറുകൾ മറയ്ക്കാനോ പൊതുവൽക്കരിക്കാനോ വെബ് സെർവർ ക്രമീകരിക്കുക.' },
    ref: '',
  },
  'sec.vuln_js': {
    category: 'security',
    severity: 'H',
    title: { en: 'Uses a JavaScript library with a known vulnerability', ml: 'അറിയപ്പെടുന്ന ദൗർബല്യമുള്ള ഒരു JavaScript ലൈബ്രറി ഉപയോഗിക്കുന്നു' },
    citizen: { en: 'The page loads a script library with a publicly known security flaw, which could let an attacker interfere with the page in your browser.', ml: 'പരസ്യമായി അറിയപ്പെടുന്ന ഒരു സുരക്ഷാ പിഴവുള്ള ഒരു സ്ക്രിപ്റ്റ് ലൈബ്രറി പേജ് ലോഡ് ചെയ്യുന്നു, ഇത് നിങ്ങളുടെ ബ്രൗസറിലെ പേജിൽ ഇടപെടാൻ ഒരു ആക്രമണകാരിയെ അനുവദിച്ചേക്കാം.' },
    fix: { en: 'Update the affected library to a version without the known vulnerability.', ml: 'ബാധിക്കപ്പെട്ട ലൈബ്രറി, അറിയപ്പെടുന്ന ദൗർബല്യം ഇല്ലാത്ത ഒരു പതിപ്പിലേക്ക് അപ്ഡേറ്റ് ചെയ്യുക.' },
    ref: 'OWASP A06:2021 Vulnerable and Outdated Components',
  },
  'sec.safe_browsing': {
    category: 'security',
    severity: 'C',
    statusSetting: 'hijacked',
    title: { en: 'Flagged by Google Safe Browsing', ml: 'Google Safe Browsing ഇത് അപകടകരമെന്ന് അടയാളപ്പെടുത്തി' },
    citizen: { en: 'An independent safety service has flagged this address as unsafe (phishing or malware). Do not enter any personal details here.', ml: 'ഒരു സ്വതന്ത്ര സുരക്ഷാ സേവനം ഈ വിലാസം സുരക്ഷിതമല്ലെന്ന് (ഫിഷിംഗ് അല്ലെങ്കിൽ മാൽവെയർ) അടയാളപ്പെടുത്തിയിരിക്കുന്നു. ഇവിടെ നിങ്ങളുടെ വ്യക്തിഗത വിവരങ്ങളൊന്നും നൽകരുത്.' },
    fix: { en: "Investigate immediately -- this usually means the site or domain was compromised. Follow Google's Safe Browsing remediation steps and request a review once fixed.", ml: 'ഉടൻ അന്വേഷിക്കുക -- സാധാരണയായി ഇതിനർത്ഥം സൈറ്റോ ഡൊമെയ്‌നോ ആക്രമിക്കപ്പെട്ടു എന്നാണ്. Google\'s Safe Browsing പരിഹാര നടപടികൾ പിന്തുടരുകയും, ശരിയാക്കിയ ശേഷം ഒരു റിവ്യൂ അഭ്യർത്ഥിക്കുകയും ചെയ്യുക.' },
    ref: '',
  },

  // ---- a11y.* -- can everyone use it? (WCAG 2.1 AA, which GIGW 3.0 mandates)
  'a11y.axe_critical': {
    category: 'accessibility',
    severity: 'H',
    title: { en: 'Critical accessibility violations', ml: 'ഗുരുതരമായ ആക്സസിബിലിറ്റി (accessibility) പ്രശ്നങ്ങൾ' },
    citizen: { en: 'Automated testing found serious accessibility problems that are very likely to block some visitors, such as screen-reader users, from using this page at all.', ml: 'സ്ക്രീൻ റീഡർ ഉപയോഗിക്കുന്നവരെ പോലുള്ള ചില സന്ദർശകർക്ക് ഈ പേജ് ഒട്ടും ഉപയോഗിക്കാൻ കഴിയാതെ വരാൻ സാധ്യതയുള്ള ഗുരുതര പ്രശ്നങ്ങൾ ഓട്ടോമേറ്റഡ് പരിശോധനയിൽ കണ്ടെത്തി.' },
    fix: { en: 'Run an accessibility scanner (e.g. axe) and fix every critical-impact violation it reports first.', ml: 'ഒരു ആക്സസിബിലിറ്റി സ്കാനർ (ഉദാ: axe) പ്രവർത്തിപ്പിച്ച്, അത് റിപ്പോർട്ട് ചെയ്യുന്ന ഏറ്റവും ഗുരുതരമായ പ്രശ്നങ്ങൾ ആദ്യം പരിഹരിക്കുക.' },
    ref: 'WCAG 2.1 AA',
  },
  'a11y.axe_serious': {
    category: 'accessibility',
    severity: 'M',
    title: { en: 'Serious accessibility violations', ml: 'ഗുരുതരമായ (serious) ആക്സസിബിലിറ്റി പ്രശ്നങ്ങൾ' },
    citizen: { en: 'Automated testing found accessibility problems likely to make parts of this page difficult to use for some visitors.', ml: 'ചില സന്ദർശകർക്ക് ഈ പേജിന്റെ ചില ഭാഗങ്ങൾ ഉപയോഗിക്കാൻ ബുദ്ധിമുട്ടുണ്ടാക്കാൻ സാധ്യതയുള്ള ആക്സസിബിലിറ്റി പ്രശ്നങ്ങൾ ഓട്ടോമേറ്റഡ് പരിശോധനയിൽ കണ്ടെത്തി.' },
    fix: { en: 'Fix the serious-impact violations an accessibility scanner reports.', ml: 'ഒരു ആക്സസിബിലിറ്റി സ്കാനർ റിപ്പോർട്ട് ചെയ്യുന്ന ഗുരുതര-സ്വാധീനമുള്ള പ്രശ്നങ്ങൾ പരിഹരിക്കുക.' },
    ref: 'WCAG 2.1 AA',
  },
  'a11y.axe_moderate_minor': {
    category: 'accessibility',
    severity: 'L',
    title: { en: 'Minor accessibility issues', ml: 'ചെറിയ ആക്സസിബിലിറ്റി പ്രശ്നങ്ങൾ' },
    citizen: { en: 'Smaller accessibility issues were found; each on its own is unlikely to block anyone, but they add up.', ml: 'ചെറിയ ആക്സസിബിലിറ്റി പ്രശ്നങ്ങൾ കണ്ടെത്തി; ഓരോന്നും ഒറ്റയ്ക്ക് ആരെയും തടയാൻ സാധ്യതയില്ല, പക്ഷേ അവ കൂടിച്ചേരുമ്പോൾ പ്രശ്നമാകും.' },
    fix: { en: 'Work through the moderate/minor findings from an accessibility scanner as time allows.', ml: 'സമയം അനുവദിക്കുന്നതനുസരിച്ച് ഒരു ആക്സസിബിലിറ്റി സ്കാനറിൽ നിന്നുള്ള മിതമായ/ചെറിയ കണ്ടെത്തലുകൾ ഘട്ടം ഘട്ടമായി പരിഹരിക്കുക.' },
    ref: 'WCAG 2.1 AA',
  },
  'a11y.lang': {
    category: 'accessibility',
    severity: 'H',
    title: { en: 'Page language is missing or wrong', ml: 'പേജിന്റെ ഭാഷ വ്യക്തമാക്കിയിട്ടില്ല അല്ലെങ്കിൽ തെറ്റാണ്' },
    citizen: { en: "A screen reader needs to know what language the page is in to pronounce it correctly -- without this, a Malayalam page read aloud in an English voice is unintelligible.", ml: 'പേജ് ശരിയായി ഉച്ചരിക്കാൻ ഏത് ഭാഷയിലാണെന്ന് സ്ക്രീൻ റീഡറിന് അറിയേണ്ടതുണ്ട് -- ഇത് ഇല്ലെങ്കിൽ, മലയാളം പേജ് ഇംഗ്ലീഷ് ശബ്ദത്തിൽ വായിക്കുമ്പോൾ അത് മനസ്സിലാക്കാൻ കഴിയാതെയാകും.' },
    fix: { en: 'Set <html lang="ml"> (or the correct language) so it matches what the page actually contains.', ml: 'പേജിൽ യഥാർത്ഥത്തിൽ ഉള്ള ഭാഷയുമായി പൊരുത്തപ്പെടുന്ന വിധം <html lang="ml"> (അല്ലെങ്കിൽ ശരിയായ ഭാഷ) സെറ്റ് ചെയ്യുക.' },
    ref: 'WCAG 2.1 SC 3.1.1',
  },
  'a11y.alt': {
    category: 'accessibility',
    severity: 'M',
    title: { en: 'Images missing alt text', ml: 'ചിത്രങ്ങൾക്ക് alt ടെക്സ്റ്റ് ഇല്ല' },
    citizen: { en: 'Someone using a screen reader hears nothing useful where an image is -- if it conveys information, that information is simply lost to them.', ml: 'സ്ക്രീൻ റീഡർ ഉപയോഗിക്കുന്ന ഒരാൾക്ക് ചിത്രമുള്ളിടത്ത് ഉപകാരപ്രദമായി ഒന്നും കേൾക്കാൻ കഴിയില്ല -- ചിത്രം എന്തെങ്കിലും വിവരം നൽകുന്നതാണെങ്കിൽ, ആ വിവരം അവർക്ക് നഷ്ടമാകും.' },
    fix: { en: 'Add descriptive alt text to every meaningful image; use alt="" only for purely decorative ones.', ml: 'അർത്ഥവത്തായ ഓരോ ചിത്രത്തിനും വിവരണാത്മകമായ alt ടെക്സ്റ്റ് ചേർക്കുക; അലങ്കാരത്തിന് മാത്രമുള്ള ചിത്രങ്ങൾക്ക് alt="" മാത്രം ഉപയോഗിക്കുക.' },
    ref: 'WCAG 2.1 SC 1.1.1',
  },
  'a11y.contrast': {
    category: 'accessibility',
    severity: 'M',
    title: { en: 'Text contrast is too low', ml: 'ടെക്സ്റ്റ് കോൺട്രാസ്റ്റ് വളരെ കുറവാണ്' },
    citizen: { en: 'Some text is hard to read against its background, especially for visitors with low vision or in bright sunlight on a phone.', ml: 'ചില ടെക്സ്റ്റ് അതിന്റെ പശ്ചാത്തലത്തിനെതിരെ വായിക്കാൻ ബുദ്ധിമുട്ടാണ്, പ്രത്യേകിച്ച് കാഴ്ച കുറവുള്ള സന്ദർശകർക്കോ ഫോണിൽ തെളിഞ്ഞ വെയിലിലോ.' },
    fix: { en: 'Darken text or lighten backgrounds until the contrast ratio meets WCAG AA (4.5:1 for normal text).', ml: 'കോൺട്രാസ്റ്റ് അനുപാതം WCAG AA (സാധാരണ ടെക്സ്റ്റിന് 4.5:1) തൃപ്തിപ്പെടുത്തുന്നതുവരെ ടെക്സ്റ്റ് ഇരുണ്ടതാക്കുകയോ പശ്ചാത്തലം തെളിച്ചമുള്ളതാക്കുകയോ ചെയ്യുക.' },
    ref: 'WCAG 2.1 SC 1.4.3',
  },
  'a11y.headings': {
    category: 'accessibility',
    severity: 'L',
    title: { en: 'Heading structure is missing or broken', ml: 'ഹെഡിംഗ് ഘടന ഇല്ല അല്ലെങ്കിൽ തകരാറാണ്' },
    citizen: { en: 'Screen-reader users often jump between sections by heading level; a missing top-level heading or skipped levels make the page harder to navigate that way.', ml: 'സ്ക്രീൻ റീഡർ ഉപയോക്താക്കൾ പലപ്പോഴും ഹെഡിംഗ് ലെവൽ വഴി വിഭാഗങ്ങൾക്കിടയിൽ ചാടാറുണ്ട്; ഒരു ടോപ്പ്-ലെവൽ ഹെഡിംഗ് ഇല്ലാതിരിക്കുകയോ ലെവലുകൾ ഒഴിവാക്കുകയോ ചെയ്താൽ ആ വിധത്തിൽ പേജ് നാവിഗേറ്റ് ചെയ്യാൻ ബുദ്ധിമുട്ടാകും.' },
    fix: { en: 'Add one <h1> per page and use heading levels in order without skipping.', ml: 'ഓരോ പേജിനും ഒരു <h1> ചേർത്ത്, ഹെഡിംഗ് ലെവലുകൾ ഒഴിവാക്കാതെ ക്രമത്തിൽ ഉപയോഗിക്കുക.' },
    ref: 'WCAG 2.1 SC 1.3.1',
  },
  'a11y.labels': {
    category: 'accessibility',
    severity: 'M',
    title: { en: 'Form fields without labels', ml: 'ലേബലുകളില്ലാത്ത ഫോം ഫീൽഡുകൾ' },
    citizen: { en: 'A screen reader cannot tell you what a form field is for if it has no associated label, making forms hard or impossible to fill in.', ml: 'ബന്ധപ്പെട്ട ലേബൽ ഇല്ലെങ്കിൽ ഒരു ഫോം ഫീൽഡ് എന്തിനുള്ളതാണെന്ന് സ്ക്രീൻ റീഡറിന് നിങ്ങളോട് പറയാൻ കഴിയില്ല, ഇത് ഫോമുകൾ പൂരിപ്പിക്കുന്നത് ബുദ്ധിമുട്ടോ അസാധ്യമോ ആക്കുന്നു.' },
    fix: { en: 'Give every form control a <label> (or aria-label) that describes what to enter.', ml: 'എന്താണ് നൽകേണ്ടതെന്ന് വിവരിക്കുന്ന ഒരു <label> (അല്ലെങ്കിൽ aria-label) ഓരോ ഫോം കൺട്രോളിനും നൽകുക.' },
    ref: 'WCAG 2.1 SC 4.1.2',
  },
  'a11y.skip_link': {
    category: 'accessibility',
    severity: 'L',
    title: { en: 'No "skip to content" link', ml: '"ഉള്ളടക്കത്തിലേക്ക് പോകുക" (skip to content) ലിങ്ക് ഇല്ല' },
    citizen: { en: 'Someone navigating by keyboard has to tab through the entire menu on every single page before reaching the actual content.', ml: 'കീബോർഡ് ഉപയോഗിച്ച് നാവിഗേറ്റ് ചെയ്യുന്ന ഒരാൾക്ക് യഥാർത്ഥ ഉള്ളടക്കത്തിൽ എത്തുന്നതിന് മുൻപ് ഓരോ പേജിലും മുഴുവൻ മെനുവിലൂടെയും ടാബ് ചെയ്യേണ്ടിവരും.' },
    fix: { en: 'Add a visible-on-focus skip link at the top of the page that jumps to the main content.', ml: 'പ്രധാന ഉള്ളടക്കത്തിലേക്ക് ചാടുന്ന, ഫോക്കസ് ചെയ്യുമ്പോൾ ദൃശ്യമാകുന്ന ഒരു സ്കിപ്പ് ലിങ്ക് പേജിന്റെ മുകളിൽ ചേർക്കുക.' },
    ref: 'WCAG 2.1 SC 2.4.1',
  },
  'a11y.keyboard': {
    category: 'accessibility',
    severity: 'L',
    title: { en: 'Possible keyboard-navigation trap', ml: 'കീബോർഡ്-നാവിഗേഷൻ കുടുക്ക് സാധ്യത' },
    citizen: { en: 'Some interactive elements may be unreachable or invisible to someone who navigates by keyboard alone rather than a mouse.', ml: 'മൗസിന് പകരം കീബോർഡ് മാത്രം ഉപയോഗിച്ച് നാവിഗേറ്റ് ചെയ്യുന്ന ഒരാൾക്ക് ചില ഇന്ററാക്ടീവ് ഘടകങ്ങൾ എത്തിച്ചേരാനോ കാണാനോ കഴിയാതെ വന്നേക്കാം.' },
    fix: { en: "Make sure every interactive element can be reached and clearly seen with the keyboard's Tab key alone.", ml: 'കീബോർഡിന്റെ Tab കീ മാത്രം ഉപയോഗിച്ച് ഓരോ ഇന്ററാക്ടീവ് ഘടകത്തിലും എത്തിച്ചേരാനും അത് വ്യക്തമായി കാണാനും കഴിയുമെന്ന് ഉറപ്പാക്കുക.' },
    ref: 'WCAG 2.1 SC 2.1.1',
  },
  'a11y.lighthouse': {
    category: 'accessibility',
    severity: 'I',
    title: { en: 'Lighthouse accessibility score', ml: 'Lighthouse ആക്സസിബിലിറ്റി സ്കോർ' },
    citizen: { en: "An automated overall accessibility score, shown for context -- it doesn't by itself change this site's status.", ml: 'ഒരു ഓട്ടോമേറ്റഡ് മൊത്തത്തിലുള്ള ആക്സസിബിലിറ്റി സ്കോർ, സന്ദർഭത്തിനായി കാണിക്കുന്നത് -- ഇത് ഒറ്റയ്ക്ക് ഈ സൈറ്റിന്റെ സ്റ്റാറ്റസ് മാറ്റുന്നില്ല.' },
    fix: { en: 'Use the specific accessibility findings above to improve this score; the number alone is not actionable.', ml: 'ഈ സ്കോർ മെച്ചപ്പെടുത്താൻ മുകളിലുള്ള നിർദ്ദിഷ്ട ആക്സസിബിലിറ്റി കണ്ടെത്തലുകൾ ഉപയോഗിക്കുക; നമ്പർ മാത്രം പ്രവർത്തനക്ഷമമല്ല.' },
    ref: '',
  },

  // ---- perf.* -- performance & mobile
  'perf.lighthouse': {
    category: 'performance',
    severity: 'I',
    title: { en: 'Lighthouse performance score', ml: 'Lighthouse പെർഫോമൻസ് സ്കോർ' },
    citizen: { en: 'An automated overall speed score on a simulated slow mobile connection, shown for context.', ml: 'ഒരു സിമുലേറ്റഡ് സ്ലോ മൊബൈൽ കണക്ഷനിൽ ഓട്ടോമേറ്റഡ് ആയി കണക്കാക്കിയ മൊത്തത്തിലുള്ള വേഗത സ്കോർ, സന്ദർഭത്തിനായി കാണിക്കുന്നത്.' },
    fix: { en: 'Use the specific performance findings (large images, slow server response, layout shift) to improve this.', ml: 'ഇത് മെച്ചപ്പെടുത്താൻ നിർദ്ദിഷ്ട പെർഫോമൻസ് കണ്ടെത്തലുകൾ (വലിയ ചിത്രങ്ങൾ, മന്ദഗതിയിലുള്ള സെർവർ പ്രതികരണം, ലേഔട്ട് ഷിഫ്റ്റ്) ഉപയോഗിക്കുക.' },
    ref: '',
  },
  'perf.lcp': {
    category: 'performance',
    severity: 'M',
    title: { en: 'Main content is slow to appear', ml: 'പ്രധാന ഉള്ളടക്കം കാണാൻ വൈകുന്നു' },
    citizen: { en: 'The largest visible element on the page (usually a heading or image) takes a long time to show up, which feels like the page is stuck.', ml: 'പേജിലെ ഏറ്റവും വലിയ ദൃശ്യ ഘടകം (സാധാരണയായി ഒരു ഹെഡിംഗോ ചിത്രമോ) കാണിക്കാൻ വളരെ സമയമെടുക്കുന്നു, ഇത് പേജ് സ്തംഭിച്ചു നിൽക്കുന്നതായി അനുഭവപ്പെടും.' },
    fix: { en: 'Optimise the largest above-the-fold image/element: compress it, size it correctly, and load it early.', ml: 'പേജ് തുറക്കുമ്പോൾ ആദ്യം കാണുന്ന ഏറ്റവും വലിയ ചിത്രം/ഘടകം മെച്ചപ്പെടുത്തുക: അത് കംപ്രസ് ചെയ്യുക, ശരിയായ വലുപ്പത്തിലാക്കുക, നേരത്തെ ലോഡ് ചെയ്യുക.' },
    ref: '',
  },
  'perf.cls': {
    category: 'performance',
    severity: 'L',
    title: { en: 'Page layout jumps around while loading', ml: 'ലോഡ് ചെയ്യുമ്പോൾ പേജ് ലേഔട്ട് ചാടിക്കൊണ്ടിരിക്കുന്നു' },
    citizen: { en: 'Text and buttons shift position as the page finishes loading, which can make you tap the wrong thing.', ml: 'പേജ് ലോഡ് പൂർത്തിയാകുമ്പോൾ ടെക്സ്റ്റും ബട്ടണുകളും സ്ഥാനം മാറുന്നു, ഇത് നിങ്ങളെ തെറ്റായ എന്തെങ്കിലും ടാപ്പ് ചെയ്യിച്ചേക്കാം.' },
    fix: { en: 'Reserve space (width/height) for images and ads before they load, instead of letting them push content around.', ml: 'ചിത്രങ്ങൾക്കും പരസ്യങ്ങൾക്കും അവ ലോഡ് ആകുന്നതിന് മുൻപ് സ്ഥലം (വീതി/ഉയരം) കരുതിവയ്ക്കുക, അവയെ ഉള്ളടക്കം തള്ളിമാറ്റാൻ അനുവദിക്കാതെ.' },
    ref: '',
  },
  'perf.weight': {
    category: 'performance',
    severity: 'M',
    title: { en: 'Homepage is very large to download', ml: 'ഹോംപേജ് ഡൗൺലോഡ് ചെയ്യാൻ വളരെ വലുതാണ്' },
    citizen: { en: 'The homepage transfers an unusually large amount of data, which is slow and can be expensive on a limited mobile data plan.', ml: 'ഹോംപേജ് അസാധാരണമാം വിധം വലിയ അളവിൽ ഡാറ്റ കൈമാറുന്നു, ഇത് വേഗത കുറഞ്ഞതും പരിമിതമായ മൊബൈൽ ഡാറ്റാ പ്ലാനിൽ ചെലവേറിയതുമാകാം.' },
    fix: { en: 'Compress images, remove unused scripts/styles, and enable gzip/br compression on the server.', ml: 'ചിത്രങ്ങൾ കംപ്രസ് ചെയ്യുക, ഉപയോഗിക്കാത്ത സ്ക്രിപ്റ്റുകൾ/സ്റ്റൈലുകൾ നീക്കം ചെയ്യുക, സെർവറിൽ gzip/br കംപ്രഷൻ പ്രാപ്തമാക്കുക.' },
    ref: '',
  },
  'perf.viewport': {
    category: 'performance',
    severity: 'H',
    title: { en: 'Not set up for mobile screens', ml: 'മൊബൈൽ സ്ക്രീനുകൾക്കായി ക്രമീകരിച്ചിട്ടില്ല' },
    citizen: { en: "Most citizens will open this on a phone; without this setting the page renders as a tiny, hard-to-read desktop layout that needs constant pinch-zooming.", ml: 'മിക്ക പൗരന്മാരും ഇത് ഫോണിൽ തുറക്കും; ഈ സെറ്റിംഗ് ഇല്ലെങ്കിൽ പേജ് ചെറിയ, വായിക്കാൻ ബുദ്ധിമുട്ടുള്ള ഡെസ്ക്ടോപ്പ് ലേഔട്ടായി കാണപ്പെടും, തുടർച്ചയായി പിഞ്ച്-സൂം ചെയ്യേണ്ടിവരും.' },
    fix: { en: 'Add <meta name="viewport" content="width=device-width, initial-scale=1">.', ml: '<meta name="viewport" content="width=device-width, initial-scale=1"> ചേർക്കുക.' },
    ref: '',
  },
  'perf.tap_targets': {
    category: 'performance',
    severity: 'M',
    title: { en: 'Buttons/links too small or close together on mobile', ml: 'മൊബൈലിൽ ബട്ടണുകൾ/ലിങ്കുകൾ വളരെ ചെറുതോ അടുത്തടുത്തോ ആണ്' },
    citizen: { en: 'On a phone, some links or buttons are small or crowded enough that it is easy to tap the wrong one.', ml: 'ഫോണിൽ, ചില ലിങ്കുകളോ ബട്ടണുകളോ ചെറുതോ തിങ്ങിനിറഞ്ഞതോ ആയതിനാൽ തെറ്റായത് ടാപ്പ് ചെയ്യുക എളുപ്പമാണ്.' },
    fix: { en: 'Increase the tap-target size and spacing for interactive elements on small screens.', ml: 'ചെറിയ സ്ക്രീനുകളിൽ ഇന്ററാക്ടീവ് ഘടകങ്ങളുടെ ടാപ്പ്-ടാർഗെറ്റ് വലുപ്പവും അകലവും വർദ്ധിപ്പിക്കുക.' },
    ref: '',
  },
  'perf.images': {
    category: 'performance',
    severity: 'L',
    title: { en: 'Images are uncompressed or oversized', ml: 'ചിത്രങ്ങൾ കംപ്രസ് ചെയ്യാത്തതോ വലുപ്പം കൂടിയതോ ആണ്' },
    citizen: { en: 'Some images are far larger than they need to be for how they are displayed, slowing the page down for no visible benefit.', ml: 'ചില ചിത്രങ്ങൾ അവ പ്രദർശിപ്പിക്കുന്ന വിധത്തിന് ആവശ്യമുള്ളതിനേക്കാൾ വളരെ വലുതാണ്, ഇത് ദൃശ്യമായ പ്രയോജനമില്ലാതെ പേജിനെ മന്ദഗതിയിലാക്കുന്നു.' },
    fix: { en: 'Resize images to their display dimensions and compress them (WebP/AVIF where possible).', ml: 'ചിത്രങ്ങൾ അവയുടെ പ്രദർശന വലുപ്പത്തിലേക്ക് മാറ്റി, കംപ്രസ് ചെയ്യുക (സാധ്യമെങ്കിൽ WebP/AVIF).' },
    ref: '',
  },

  // ---- content.* -- is anyone looking after it?
  'content.copyright_year': {
    category: 'content',
    severity: 'M',
    title: { en: 'Footer copyright year is old', ml: 'ഫൂട്ടറിലെ കോപ്പിറൈറ്റ് വർഷം പഴയതാണ്' },
    citizen: { en: 'The copyright year in the footer is at least two years out of date, a small but visible sign nobody has touched this site recently.', ml: 'ഫൂട്ടറിലെ കോപ്പിറൈറ്റ് വർഷം ചുരുങ്ങിയത് രണ്ട് വർഷമെങ്കിലും പഴയതാണ്, ഈ സൈറ്റ് അടുത്തിടെ ആരും തൊട്ടിട്ടില്ല എന്നതിന്റെ ചെറുതെങ്കിലും ദൃശ്യമായ ഒരു സൂചന.' },
    fix: { en: 'Update the footer copyright year, ideally to update automatically each year.', ml: 'ഫൂട്ടർ കോപ്പിറൈറ്റ് വർഷം അപ്ഡേറ്റ് ചെയ്യുക, ഓരോ വർഷവും സ്വയമേവ അപ്ഡേറ്റ് ആകുന്നതാണ് നല്ലത്.' },
    ref: '',
  },
  'content.last_updated': {
    category: 'content',
    severity: 'H',
    title: { en: '"Last updated" date is missing or very old', ml: '"അവസാനമായി പുതുക്കിയത്" തീയതി ഇല്ല അല്ലെങ്കിൽ വളരെ പഴയതാണ്' },
    citizen: { en: "There's no visible sign of when this page was last reviewed, or the date shown is over a year old -- you can't tell whether the information is still current.", ml: 'ഈ പേജ് അവസാനം എപ്പോൾ പരിശോധിച്ചു എന്നതിന് ദൃശ്യമായ സൂചനയില്ല, അല്ലെങ്കിൽ കാണിക്കുന്ന തീയതി ഒരു വർഷത്തിലേറെ പഴയതാണ് -- വിവരങ്ങൾ ഇപ്പോഴും കാലികമാണോ എന്ന് നിങ്ങൾക്ക് അറിയാൻ കഴിയില്ല.' },
    fix: { en: 'Show a genuine last-reviewed/updated date on every content page, and actually keep it current.', ml: 'ഓരോ ഉള്ളടക്ക പേജിലും യഥാർത്ഥമായ അവസാനം-പരിശോധിച്ച/പുതുക്കിയ തീയതി കാണിക്കുക, അത് യഥാർത്ഥത്തിൽ കാലികമായി സൂക്ഷിക്കുകയും ചെയ്യുക.' },
    ref: 'GIGW 3.0',
  },
  'content.stale_news': {
    category: 'content',
    severity: 'M',
    title: { en: 'News/announcements section is stale', ml: 'വാർത്ത/അറിയിപ്പ് വിഭാഗം കാലഹരണപ്പെട്ടതാണ്' },
    citizen: { en: 'The newest item in the news, announcements or tenders section is over a year old, suggesting this part of the site is no longer maintained.', ml: 'വാർത്ത, അറിയിപ്പുകൾ അല്ലെങ്കിൽ ടെൻഡറുകൾ വിഭാഗത്തിലെ ഏറ്റവും പുതിയ ഇനം ഒരു വർഷത്തിലേറെ പഴയതാണ്, ഇത് സൈറ്റിന്റെ ഈ ഭാഗം ഇനി പരിപാലിക്കുന്നില്ലെന്ന് സൂചിപ്പിക്കുന്നു.' },
    fix: { en: 'Post current announcements, or remove the section if it is no longer in use.', ml: 'നിലവിലെ അറിയിപ്പുകൾ പോസ്റ്റ് ചെയ്യുക, അല്ലെങ്കിൽ ഇനി ഉപയോഗത്തിലില്ലെങ്കിൽ ഈ വിഭാഗം നീക്കം ചെയ്യുക.' },
    ref: '',
  },
  'content.placeholder': {
    category: 'content',
    severity: 'H',
    title: { en: 'Placeholder text left on the live site', ml: 'ലൈവ് സൈറ്റിൽ പ്ലേസ്ഹോൾഡർ ടെക്സ്റ്റ് ബാക്കിയുണ്ട്' },
    citizen: { en: 'The page still shows template filler text ("Lorem ipsum", "sample text", "Home page description") instead of real content.', ml: 'യഥാർത്ഥ ഉള്ളടക്കത്തിന് പകരം പേജ് ഇപ്പോഴും ടെംപ്ലേറ്റ് ഫില്ലർ ടെക്സ്റ്റ് ("Lorem ipsum", "sample text", "Home page description" പോലുള്ളവ) കാണിക്കുന്നു.' },
    fix: { en: 'Replace every placeholder string with the real content it was standing in for.', ml: 'ഓരോ പ്ലേസ്ഹോൾഡർ ടെക്സ്റ്റും അതിന് പകരം വരേണ്ട യഥാർത്ഥ ഉള്ളടക്കം ഉപയോഗിച്ച് മാറ്റിസ്ഥാപിക്കുക.' },
    ref: '',
  },
  'content.legacy_font': {
    category: 'content',
    severity: 'H',
    title: { en: 'Uses a non-Unicode Malayalam font', ml: 'യൂണികോഡ് അല്ലാത്ത ഒരു മലയാളം ഫോണ്ട് ഉപയോഗിക്കുന്നു' },
    citizen: { en: 'This page uses an old-style Malayalam font (like ML-TTKarthika or ISM/Matweb) that only displays correctly if you happen to have that exact font installed -- for everyone else, the text is unreadable garbled characters.', ml: 'ഈ പേജ് ഒരു പഴയ-രീതി മലയാളം ഫോണ്ട് (ML-TTKarthika അല്ലെങ്കിൽ ISM/Matweb പോലുള്ളവ) ഉപയോഗിക്കുന്നു, നിങ്ങളുടെ കമ്പ്യൂട്ടറിൽ കൃത്യമായി ആ ഫോണ്ട് ഇൻസ്റ്റോൾ ചെയ്തിട്ടുണ്ടെങ്കിൽ മാത്രമേ ഇത് ശരിയായി കാണിക്കൂ -- മറ്റെല്ലാവർക്കും, ടെക്സ്റ്റ് വായിക്കാൻ കഴിയാത്ത കുഴഞ്ഞ അക്ഷരങ്ങളാണ്.' },
    fix: { en: 'Switch to a Unicode Malayalam font (e.g. Manjari, Noto Sans Malayalam) so the text reads correctly for everyone, with no font install required.', ml: 'എല്ലാവർക്കും ടെക്സ്റ്റ് ശരിയായി വായിക്കാൻ കഴിയുന്ന വിധം, ഫോണ്ട് ഇൻസ്റ്റോൾ ചെയ്യേണ്ട ആവശ്യമില്ലാതെ, ഒരു യൂണികോഡ് മലയാളം ഫോണ്ടിലേക്ക് (ഉദാ: Manjari, Noto Sans Malayalam) മാറുക.' },
    ref: '',
  },
  'content.obsolete_tech': {
    category: 'content',
    severity: 'M',
    title: { en: 'Uses obsolete web technology', ml: 'കാലഹരണപ്പെട്ട വെബ് സാങ്കേതികവിദ്യ ഉപയോഗിക്കുന്നു' },
    citizen: { en: 'This page uses old technology (Flash, Java applets, <marquee>/<blink>, frames) that modern browsers no longer support at all, so part of the page may simply not work.', ml: 'ഈ പേജ് പഴയ സാങ്കേതികവിദ്യ (Flash, Java applets, <marquee>/<blink>, frames) ഉപയോഗിക്കുന്നു, ആധുനിക ബ്രൗസറുകൾ ഇവ ഇനി ഒട്ടും പിന്തുണയ്ക്കുന്നില്ല, അതിനാൽ പേജിന്റെ ഭാഗം പ്രവർത്തിക്കണമെന്നില്ല.' },
    fix: { en: 'Replace Flash/Java-applet content and framesets with modern HTML/CSS/JS equivalents.', ml: 'Flash/Java-applet ഉള്ളടക്കവും ഫ്രെയിംസെറ്റുകളും ആധുനിക HTML/CSS/JS തുല്യങ്ങൾ ഉപയോഗിച്ച് മാറ്റിസ്ഥാപിക്കുക.' },
    ref: '',
  },
  'content.best_viewed': {
    category: 'content',
    severity: 'L',
    title: { en: '"Best viewed in..." notice', ml: '"ഇതിൽ ഏറ്റവും നന്നായി കാണാം..." (Best viewed in) അറിയിപ്പ്' },
    citizen: { en: 'The site tells you it was only designed for one specific old browser or screen size, a sign it has not been updated for how people browse today.', ml: 'ഒരു നിർദ്ദിഷ്ട പഴയ ബ്രൗസറിനോ സ്ക്രീൻ വലുപ്പത്തിനോ വേണ്ടി മാത്രമാണ് ഇത് രൂപകൽപ്പന ചെയ്തതെന്ന് സൈറ്റ് പറയുന്നു, ഇന്ന് ആളുകൾ ബ്രൗസ് ചെയ്യുന്ന രീതിക്കനുസരിച്ച് ഇത് അപ്ഡേറ്റ് ചെയ്തിട്ടില്ല എന്നതിന്റെ സൂചന.' },
    fix: { en: 'Remove the notice and make the site work properly in current, common browsers and screen sizes instead.', ml: 'അറിയിപ്പ് നീക്കം ചെയ്ത്, പകരം ഇന്നത്തെ സാധാരണ ബ്രൗസറുകളിലും സ്ക്രീൻ വലുപ്പങ്ങളിലും സൈറ്റ് ശരിയായി പ്രവർത്തിക്കുന്നതാക്കുക.' },
    ref: '',
  },
  'content.broken_links': {
    category: 'content',
    severity: 'H',
    title: { en: 'Broken internal links', ml: 'പ്രവർത്തിക്കാത്ത ആന്തരിക ലിങ്കുകൾ' },
    citizen: { en: 'Some links on this site lead to pages that no longer exist or time out, which is frustrating and can hide information you were looking for.', ml: 'ഈ സൈറ്റിലെ ചില ലിങ്കുകൾ ഇനി നിലവിലില്ലാത്ത പേജുകളിലേക്ക് നയിക്കുന്നു, അല്ലെങ്കിൽ സമയപരിധി കഴിയുന്നു -- ഇത് അസ്വസ്ഥതയുണ്ടാക്കുന്നതും, നിങ്ങൾ തിരയുന്ന വിവരം മറഞ്ഞുപോകാൻ കാരണവുമാകാം.' },
    fix: { en: 'Fix or remove each broken link; if the target page moved, add a redirect.', ml: 'ഓരോ പ്രവർത്തിക്കാത്ത ലിങ്കും ശരിയാക്കുക അല്ലെങ്കിൽ നീക്കം ചെയ്യുക; ലക്ഷ്യ പേജ് മാറിയിട്ടുണ്ടെങ്കിൽ ഒരു റീഡയറക്ട് ചേർക്കുക.' },
    ref: '',
  },
  'content.broken_pdfs': {
    category: 'content',
    severity: 'M',
    title: { en: 'Linked PDFs are missing', ml: 'ലിങ്ക് ചെയ്ത PDF-കൾ കാണുന്നില്ല' },
    citizen: { en: 'Some linked documents (forms, notices, reports) 404 instead of downloading, which can block you from getting an official document you need.', ml: 'ചില ലിങ്ക് ചെയ്ത രേഖകൾ (ഫോമുകൾ, അറിയിപ്പുകൾ, റിപ്പോർട്ടുകൾ) ഡൗൺലോഡ് ചെയ്യുന്നതിന് പകരം 404 കാണിക്കുന്നു, ഇത് നിങ്ങൾക്ക് ആവശ്യമായ ഒരു ഔദ്യോഗിക രേഖ ലഭിക്കുന്നതിൽ നിന്ന് നിങ്ങളെ തടഞ്ഞേക്കാം.' },
    fix: { en: 'Re-upload the missing PDFs at their linked URLs, or update the links to where they now live.', ml: 'കാണാതായ PDF-കൾ അവയുടെ ലിങ്ക് ചെയ്ത URL-കളിൽ വീണ്ടും അപ്‌ലോഡ് ചെയ്യുക, അല്ലെങ്കിൽ അവ ഇപ്പോൾ എവിടെയാണെന്ന് ലിങ്കുകൾ അപ്ഡേറ്റ് ചെയ്യുക.' },
    ref: '',
  },
  'content.broken_images': {
    category: 'content',
    severity: 'L',
    title: { en: 'Broken images', ml: 'പ്രവർത്തിക്കാത്ത ചിത്രങ്ങൾ' },
    citizen: { en: 'Some images fail to load, leaving broken-image icons on the page.', ml: 'ചില ചിത്രങ്ങൾ ലോഡ് ആകുന്നില്ല, പേജിൽ പ്രവർത്തിക്കാത്ത-ചിത്ര ഐക്കണുകൾ ബാക്കിയാകുന്നു.' },
    fix: { en: 'Fix or remove the broken image references.', ml: 'പ്രവർത്തിക്കാത്ത ചിത്ര റഫറൻസുകൾ ശരിയാക്കുക അല്ലെങ്കിൽ നീക്കം ചെയ്യുക.' },
    ref: '',
  },
  'content.malayalam': {
    category: 'content',
    severity: 'M',
    title: { en: 'No Malayalam version available', ml: 'മലയാളം പതിപ്പ് ലഭ്യമല്ല' },
    citizen: { en: "This citizen-facing site has no Malayalam version or toggle, which shuts out anyone more comfortable reading Malayalam than English.", ml: 'പൗരന്മാർക്കായുള്ള ഈ സൈറ്റിന് മലയാളം പതിപ്പോ ടോഗിളോ ഇല്ല, ഇംഗ്ലീഷിനേക്കാൾ മലയാളം വായിക്കാൻ സൗകര്യമുള്ളവരെ ഇത് പുറന്തള്ളുന്നു.' },
    fix: { en: 'Add a Malayalam translation (or at minimum the key citizen-facing pages) with an easy language toggle.', ml: 'എളുപ്പമുള്ള ഭാഷാ ടോഗിളോടെ ഒരു മലയാളം വിവർത്തനം (അല്ലെങ്കിൽ ചുരുങ്ങിയത് പ്രധാന പൗരൻ-അഭിമുഖ പേജുകളെങ്കിലും) ചേർക്കുക.' },
    ref: '',
  },
  'content.title': {
    category: 'content',
    severity: 'M',
    title: { en: 'Page title is missing or generic', ml: 'പേജ് ടൈറ്റിൽ ഇല്ല അല്ലെങ്കിൽ പൊതുവായതാണ്' },
    citizen: { en: 'The browser tab/bookmark/search-result title just says something like "Home" or "Untitled" instead of naming the actual organisation or page.', ml: 'യഥാർത്ഥ സ്ഥാപനത്തിന്റെയോ പേജിന്റെയോ പേര് പറയുന്നതിന് പകരം, ബ്രൗസർ ടാബ്/ബുക്ക്മാർക്ക്/സെർച്ച്-റിസൾട്ട് ടൈറ്റിൽ "Home" അല്ലെങ്കിൽ "Untitled" പോലെ എന്തെങ്കിലും മാത്രം പറയുന്നു.' },
    fix: { en: 'Give every page a specific, descriptive <title>.', ml: 'ഓരോ പേജിനും നിർദ്ദിഷ്ടവും വിവരണാത്മകവുമായ ഒരു <title> നൽകുക.' },
    ref: '',
  },
  'content.meta_desc': {
    category: 'content',
    severity: 'L',
    title: { en: 'No meta description', ml: 'മെറ്റാ വിവരണം (meta description) ഇല്ല' },
    citizen: { en: 'Search engines have nothing useful to show as a summary of this page in search results.', ml: 'സെർച്ച് റിസൾട്ടുകളിൽ ഈ പേജിന്റെ സംഗ്രഹമായി കാണിക്കാൻ സെർച്ച് എഞ്ചിനുകൾക്ക് ഉപകാരപ്രദമായി ഒന്നുമില്ല.' },
    fix: { en: 'Add a concise <meta name="description"> summarising each page.', ml: 'ഓരോ പേജും സംഗ്രഹിക്കുന്ന ഒരു ചെറിയ <meta name="description"> ചേർക്കുക.' },
    ref: '',
  },
  'content.favicon': {
    category: 'content',
    severity: 'L',
    title: { en: 'No favicon', ml: 'ഫേവിക്കൺ (favicon) ഇല്ല' },
    citizen: { en: "The site has no small icon shown in browser tabs and bookmarks, a minor but very visible polish gap.", ml: 'ബ്രൗസർ ടാബുകളിലും ബുക്ക്മാർക്കുകളിലും കാണിക്കുന്ന ചെറിയ ഐക്കൺ സൈറ്റിന് ഇല്ല, ഒരു ചെറുതെങ്കിലും വളരെ ദൃശ്യമായ പോളിഷ് കുറവ്.' },
    fix: { en: 'Add a favicon.ico (or modern equivalent) to the site.', ml: 'സൈറ്റിൽ ഒരു favicon.ico (അല്ലെങ്കിൽ ആധുനിക തുല്യമായത്) ചേർക്കുക.' },
    ref: '',
  },
  'content.console_errors': {
    category: 'content',
    severity: 'L',
    title: { en: 'JavaScript errors on load', ml: 'ലോഡ് ചെയ്യുമ്പോൾ JavaScript പിശകുകൾ' },
    citizen: { en: "The page's own code fails partway through loading, which can silently break some feature on the page without any visible error message.", ml: 'പേജിന്റെ സ്വന്തം കോഡ് ലോഡ് ചെയ്യുന്നതിനിടയിൽ പരാജയപ്പെടുന്നു, ഇത് ദൃശ്യമായ പിശക് സന്ദേശമൊന്നും കൂടാതെ പേജിലെ ചില ഫീച്ചർ നിശബ്ദമായി തകർത്തേക്കാം.' },
    fix: { en: "Open the browser's developer console on this page and fix the reported script errors.", ml: 'ഈ പേജിൽ ബ്രൗസറിന്റെ ഡെവലപ്പർ കൺസോൾ തുറന്ന്, റിപ്പോർട്ട് ചെയ്ത സ്ക്രിപ്റ്റ് പിശകുകൾ പരിഹരിക്കുക.' },
    ref: '',
  },

  // ---- gigw.* -- does it have what GIGW 3.0 says every government site must have?
  'gigw.contact': {
    category: 'gigw',
    severity: 'H',
    title: { en: 'No "Contact Us" page', ml: '"സമ്പർക്കം ചെയ്യുക" (Contact Us) പേജ് ഇല്ല' },
    citizen: { en: 'There is no clear way to find out how to contact this office by phone, email or post.', ml: 'ഫോൺ, ഇമെയിൽ അല്ലെങ്കിൽ തപാൽ വഴി ഈ ഓഫീസുമായി എങ്ങനെ ബന്ധപ്പെടാം എന്ന് കണ്ടെത്താൻ വ്യക്തമായ മാർഗമില്ല.' },
    fix: { en: 'Add a Contact Us page with a real phone number, email and postal address.', ml: 'യഥാർത്ഥ ഫോൺ നമ്പർ, ഇമെയിൽ, തപാൽ വിലാസം എന്നിവയോടെ ഒരു Contact Us പേജ് ചേർക്കുക.' },
    ref: 'GIGW 3.0',
  },
  'gigw.feedback': {
    category: 'gigw',
    severity: 'L',
    title: { en: 'No feedback mechanism', ml: 'ഫീഡ്ബാക്ക് സംവിധാനം ഇല്ല' },
    citizen: { en: 'There is no way to send feedback about the site itself.', ml: 'സൈറ്റിനെക്കുറിച്ച് ഫീഡ്ബാക്ക് അയക്കാൻ ഒരു മാർഗവുമില്ല.' },
    fix: { en: 'Add a feedback form or a dedicated feedback email address.', ml: 'ഒരു ഫീഡ്ബാക്ക് ഫോം അല്ലെങ്കിൽ പ്രത്യേക ഫീഡ്ബാക്ക് ഇമെയിൽ വിലാസം ചേർക്കുക.' },
    ref: 'GIGW 3.0',
  },
  'gigw.sitemap': {
    category: 'gigw',
    severity: 'M',
    title: { en: 'No sitemap page', ml: 'സൈറ്റ്മാപ്പ് പേജ് ഇല്ല' },
    citizen: { en: "There is no page listing everything the site contains, making it harder to find something that isn't in the main menu.", ml: 'സൈറ്റിൽ എന്തെല്ലാം ഉണ്ടെന്ന് പട്ടികപ്പെടുത്തുന്ന ഒരു പേജ് ഇല്ല, പ്രധാന മെനുവിലില്ലാത്ത എന്തെങ്കിലും കണ്ടെത്തുന്നത് ഇത് ബുദ്ധിമുട്ടാക്കുന്നു.' },
    fix: { en: 'Add a human-readable sitemap page linking every major section.', ml: 'എല്ലാ പ്രധാന വിഭാഗങ്ങളും ലിങ്ക് ചെയ്യുന്ന, മനുഷ്യർക്ക് വായിക്കാവുന്ന ഒരു സൈറ്റ്മാപ്പ് പേജ് ചേർക്കുക.' },
    ref: 'GIGW 3.0',
  },
  'gigw.privacy': {
    category: 'gigw',
    severity: 'M',
    title: { en: 'No Privacy Policy', ml: 'സ്വകാര്യതാ നയം (Privacy Policy) ഇല്ല' },
    citizen: { en: "There is no statement telling you what personal information this site collects about you or what it does with it.", ml: 'ഈ സൈറ്റ് നിങ്ങളെക്കുറിച്ച് എന്ത് വ്യക്തിഗത വിവരങ്ങൾ ശേഖരിക്കുന്നു, അവ ഉപയോഗിച്ച് എന്ത് ചെയ്യുന്നു എന്ന് പറയുന്ന ഒരു പ്രസ്താവനയും ഇല്ല.' },
    fix: { en: 'Publish a Privacy Policy page and link it from the footer of every page.', ml: 'ഒരു സ്വകാര്യതാ നയം (Privacy Policy) പേജ് പ്രസിദ്ധീകരിച്ച്, എല്ലാ പേജിന്റെയും ഫൂട്ടറിൽ അതിലേക്ക് ലിങ്ക് ചെയ്യുക.' },
    ref: 'GIGW 3.0',
  },
  'gigw.terms': {
    category: 'gigw',
    severity: 'L',
    title: { en: 'No Terms & Conditions / Terms of Use', ml: 'നിബന്ധനകളും വ്യവസ്ഥകളും (Terms & Conditions) ഇല്ല' },
    citizen: { en: 'There is no page setting out the terms for using this site.', ml: 'ഈ സൈറ്റ് ഉപയോഗിക്കുന്നതിനുള്ള നിബന്ധനകൾ വ്യക്തമാക്കുന്ന ഒരു പേജ് ഇല്ല.' },
    fix: { en: 'Publish a Terms of Use page.', ml: 'ഒരു Terms of Use പേജ് പ്രസിദ്ധീകരിക്കുക.' },
    ref: 'GIGW 3.0',
  },
  'gigw.copyright_policy': {
    category: 'gigw',
    severity: 'L',
    title: { en: 'No Copyright Policy', ml: 'കോപ്പിറൈറ്റ് നയം (Copyright Policy) ഇല്ല' },
    citizen: { en: 'There is no statement about who owns the content on this site and how it may be reused.', ml: 'ഈ സൈറ്റിലെ ഉള്ളടക്കത്തിന്റെ ഉടമസ്ഥത ആർക്കാണെന്നും അത് എങ്ങനെ വീണ്ടും ഉപയോഗിക്കാമെന്നും ഉള്ള പ്രസ്താവന ഇല്ല.' },
    fix: { en: 'Publish a Copyright Policy page.', ml: 'ഒരു Copyright Policy പേജ് പ്രസിദ്ധീകരിക്കുക.' },
    ref: 'GIGW 3.0',
  },
  'gigw.hyperlink_policy': {
    category: 'gigw',
    severity: 'L',
    title: { en: 'No Hyperlinking Policy', ml: 'ഹൈപ്പർലിങ്കിംഗ് നയം (Hyperlinking Policy) ഇല്ല' },
    citizen: { en: 'There is no statement about how this site handles links to and from other websites.', ml: 'മറ്റ് വെബ്സൈറ്റുകളിലേക്കും അവയിൽ നിന്നുമുള്ള ലിങ്കുകൾ ഈ സൈറ്റ് എങ്ങനെ കൈകാര്യം ചെയ്യുന്നു എന്നതിനെക്കുറിച്ചുള്ള പ്രസ്താവന ഇല്ല.' },
    fix: { en: 'Publish a Hyperlinking Policy page.', ml: 'ഒരു Hyperlinking Policy പേജ് പ്രസിദ്ധീകരിക്കുക.' },
    ref: 'GIGW 3.0',
  },
  'gigw.disclaimer': {
    category: 'gigw',
    severity: 'L',
    title: { en: 'No Disclaimer', ml: 'നിരാകരണം (Disclaimer) ഇല്ല' },
    citizen: { en: 'There is no disclaimer covering the accuracy or official status of the information on this site.', ml: 'ഈ സൈറ്റിലെ വിവരങ്ങളുടെ കൃത്യതയോ ഔദ്യോഗിക പദവിയോ സംബന്ധിച്ച നിരാകരണം ഇല്ല.' },
    fix: { en: 'Publish a Disclaimer page.', ml: 'ഒരു Disclaimer പേജ് പ്രസിദ്ധീകരിക്കുക.' },
    ref: 'GIGW 3.0',
  },
  'gigw.accessibility_statement': {
    category: 'gigw',
    severity: 'M',
    title: { en: 'No Accessibility Statement', ml: 'ആക്സസിബിലിറ്റി പ്രസ്താവന (Accessibility Statement) ഇല്ല' },
    citizen: { en: 'There is no page explaining the site\'s accessibility commitments or how to report an accessibility problem.', ml: 'സൈറ്റിന്റെ ആക്സസിബിലിറ്റി പ്രതിബദ്ധതകളോ ഒരു ആക്സസിബിലിറ്റി പ്രശ്നം എങ്ങനെ റിപ്പോർട്ട് ചെയ്യാമെന്നോ വിശദീകരിക്കുന്ന പേജ് ഇല്ല.' },
    fix: { en: 'Publish an Accessibility Statement with a way to report barriers.', ml: 'തടസ്സങ്ങൾ റിപ്പോർട്ട് ചെയ്യാനുള്ള മാർഗത്തോടെ ഒരു Accessibility Statement പ്രസിദ്ധീകരിക്കുക.' },
    ref: 'GIGW 3.0',
  },
  'gigw.screen_reader': {
    category: 'gigw',
    severity: 'L',
    title: { en: 'No Screen Reader Access page', ml: 'സ്ക്രീൻ റീഡർ ആക്സസ് (Screen Reader Access) പേജ് ഇല്ല' },
    citizen: { en: 'There is no page pointing screen-reader users to compatible software or usage tips for this site.', ml: 'ഈ സൈറ്റിനായി അനുയോജ്യമായ സോഫ്റ്റ്‌വെയറിലേക്കോ ഉപയോഗ നിർദ്ദേശങ്ങളിലേക്കോ സ്ക്രീൻ റീഡർ ഉപയോക്താക്കളെ നയിക്കുന്ന പേജ് ഇല്ല.' },
    fix: { en: 'Publish a Screen Reader Access page (GIGW\'s traditional term for this).', ml: 'ഒരു Screen Reader Access പേജ് പ്രസിദ്ധീകരിക്കുക (GIGW ഇതിനായി പരമ്പരാഗതമായി ഉപയോഗിക്കുന്ന പേര്).' },
    ref: 'GIGW 3.0',
  },
  'gigw.help': {
    category: 'gigw',
    severity: 'L',
    title: { en: 'No Help page', ml: 'സഹായം (Help) പേജ് ഇല്ല' },
    citizen: { en: 'There is no page explaining how to use the site itself (navigation, search, common tasks).', ml: 'സൈറ്റ് തന്നെ എങ്ങനെ ഉപയോഗിക്കാം (നാവിഗേഷൻ, തിരയൽ, സാധാരണ ജോലികൾ) എന്ന് വിശദീകരിക്കുന്ന പേജ് ഇല്ല.' },
    fix: { en: 'Publish a Help page.', ml: 'ഒരു Help പേജ് പ്രസിദ്ധീകരിക്കുക.' },
    ref: 'GIGW 3.0',
  },
  'gigw.rti': {
    category: 'gigw',
    severity: 'H',
    title: { en: 'No RTI / Public Information Officer details', ml: 'RTI / പബ്ലിക് ഇൻഫർമേഷൻ ഓഫീസർ വിവരങ്ങൾ ഇല്ല' },
    citizen: { en: "You cannot find who to contact to file a Right to Information request with this office, which is a legal right, not a courtesy.", ml: 'വിവരാവകാശ (RTI) അപേക്ഷ ഈ ഓഫീസിൽ എങ്ങനെ ഫയൽ ചെയ്യാമെന്ന് നിങ്ങൾക്ക് കണ്ടെത്താൻ കഴിയുന്നില്ല -- ഇത് ഒരു ഔദാര്യമല്ല, നിയമപരമായ അവകാശമാണ്.' },
    fix: { en: "Publish the designated Public Information Officer's name, address and contact details, and how to file an RTI request.", ml: 'നിശ്ചയിക്കപ്പെട്ട പബ്ലിക് ഇൻഫർമേഷൻ ഓഫീസറുടെ പേര്, വിലാസം, ബന്ധപ്പെടാനുള്ള വിവരങ്ങൾ, RTI അപേക്ഷ എങ്ങനെ ഫയൽ ചെയ്യാം എന്നിവ പ്രസിദ്ധീകരിക്കുക.' },
    ref: 'RTI Act 2005 s.4',
  },
  'gigw.search': {
    category: 'gigw',
    severity: 'L',
    title: { en: 'No site search', ml: 'സൈറ്റ് സെർച്ച് ഇല്ല' },
    citizen: { en: 'There is no way to search this site directly; you have to browse the menu to find anything.', ml: 'ഈ സൈറ്റ് നേരിട്ട് തിരയാൻ ഒരു മാർഗവുമില്ല; എന്തെങ്കിലും കണ്ടെത്താൻ നിങ്ങൾ മെനു ബ്രൗസ് ചെയ്യേണ്ടിവരും.' },
    fix: { en: 'Add a site search facility.', ml: 'ഒരു സൈറ്റ് സെർച്ച് സൗകര്യം ചേർക്കുക.' },
    ref: 'GIGW 3.0',
  },
  'gigw.ownership': {
    category: 'gigw',
    severity: 'M',
    title: { en: 'No content-ownership statement', ml: 'ഉള്ളടക്ക-ഉടമസ്ഥത പ്രസ്താവന ഇല്ല' },
    citizen: { en: 'There is no footer statement saying which department owns this content and who built/hosts the site, making it harder to tell an official site from an impersonation.', ml: 'ഏത് വകുപ്പിനാണ് ഈ ഉള്ളടക്കത്തിന്റെ ഉടമസ്ഥതയെന്നും ആരാണ് സൈറ്റ് നിർമ്മിച്ചത്/ഹോസ്റ്റ് ചെയ്യുന്നതെന്നും പറയുന്ന ഫൂട്ടർ പ്രസ്താവന ഇല്ല, ഇത് ഒരു ഔദ്യോഗിക സൈറ്റിനെ ഒരു ആൾമാറാട്ടത്തിൽ നിന്ന് വേർതിരിച്ചറിയുന്നത് ബുദ്ധിമുട്ടാക്കുന്നു.' },
    fix: { en: 'Add a footer statement: "Content owned by <department> — Designed, developed & hosted by <agency>".', ml: 'ഒരു ഫൂട്ടർ പ്രസ്താവന ചേർക്കുക: "ഉള്ളടക്കം <വകുപ്പ്> ന്റെ ഉടമസ്ഥതയിൽ — <ഏജൻസി> രൂപകൽപ്പന ചെയ്ത്, വികസിപ്പിച്ച്, ഹോസ്റ്റ് ചെയ്യുന്നു".' },
    ref: 'GIGW 3.0',
  },
  'gigw.last_updated': {
    category: 'gigw',
    severity: 'M',
    title: { en: 'No last-updated date shown', ml: 'അവസാനം പുതുക്കിയ തീയതി കാണിക്കുന്നില്ല' },
    citizen: { en: 'There is no visible date telling you when the site (not just one page) was last updated.', ml: 'സൈറ്റ് (ഒരു പേജ് മാത്രമല്ല) അവസാനം എപ്പോൾ പുതുക്കി എന്ന് പറയുന്ന ദൃശ്യമായ തീയതി ഇല്ല.' },
    fix: { en: 'Show a site-wide last-updated date, typically in the footer.', ml: 'സാധാരണയായി ഫൂട്ടറിൽ, സൈറ്റ്-വ്യാപകമായ അവസാനം-പുതുക്കിയ തീയതി കാണിക്കുക.' },
    ref: 'GIGW 3.0',
  },
  'gigw.emblem': {
    category: 'gigw',
    severity: 'I',
    title: { en: 'No state/national emblem shown', ml: 'സംസ്ഥാന/ദേശീയ ചിഹ്നം കാണിക്കുന്നില്ല' },
    citizen: { en: 'The site does not display the state or national emblem that citizens usually look for to help recognise an official government site.', ml: 'ഒരു ഔദ്യോഗിക സർക്കാർ സൈറ്റ് തിരിച്ചറിയാൻ പൗരന്മാർ സാധാരണയായി നോക്കുന്ന സംസ്ഥാന അല്ലെങ്കിൽ ദേശീയ ചിഹ്നം സൈറ്റ് പ്രദർശിപ്പിക്കുന്നില്ല.' },
    fix: { en: 'Display the appropriate emblem, used correctly per government branding guidelines.', ml: 'സർക്കാർ ബ്രാൻഡിംഗ് മാർഗ്ഗനിർദ്ദേശങ്ങൾ അനുസരിച്ച് ശരിയായി ഉപയോഗിച്ച്, ഉചിതമായ ചിഹ്നം പ്രദർശിപ്പിക്കുക.' },
    ref: 'GIGW 3.0',
  },

  // ---- id.* -- identity & hygiene
  'id.gov_domain': {
    category: 'identity',
    severity: 'H',
    title: { en: 'Not on an official government domain', ml: 'ഔദ്യോഗിക സർക്കാർ ഡൊമെയ്നിൽ അല്ല' },
    citizen: { en: "This site is on a .com/.org/.in/.net address rather than .gov.in/.nic.in/.kerala.gov.in/.ac.in/.edu.in. You cannot tell it apart from a phishing copycat by the address alone, and these domains can lapse and be bought by someone else.", ml: '.gov.in/.nic.in/.kerala.gov.in/.ac.in/.edu.in എന്നിവയ്ക്ക് പകരം ഈ സൈറ്റ് .com/.org/.in/.net പോലുള്ള വിലാസത്തിലാണ്. വിലാസം മാത്രം നോക്കി ഇത് ഒരു ഫിഷിംഗ് കോപ്പിയിൽ നിന്ന് വേർതിരിച്ചറിയാൻ നിങ്ങൾക്ക് കഴിയില്ല, കൂടാതെ ഇത്തരം ഡൊമെയ്നുകൾ കാലഹരണപ്പെട്ട് മറ്റാരെങ്കിലും വാങ്ങാനും സാധ്യതയുണ്ട്.' },
    fix: { en: 'Migrate to an official government domain (.gov.in/.nic.in via NIC, or .kerala.gov.in) as soon as practical.', ml: 'കഴിയുന്നത്ര വേഗം ഒരു ഔദ്യോഗിക സർക്കാർ ഡൊമെയ്നിലേക്ക് (NIC വഴി .gov.in/.nic.in, അല്ലെങ്കിൽ .kerala.gov.in) മാറുക.' },
    ref: '',
  },
  'id.domain_expiry': {
    category: 'identity',
    severity: 'H',
    title: { en: 'Domain registration is about to expire', ml: 'ഡൊമെയ്ൻ രജിസ്ട്രേഷൻ കാലഹരണപ്പെടാൻ പോകുന്നു' },
    citizen: { en: 'If this domain lapses, someone else can register it and impersonate this office to the public.', ml: 'ഈ ഡൊമെയ്ൻ കാലഹരണപ്പെട്ടാൽ, മറ്റാർക്കെങ്കിലും അത് രജിസ്റ്റർ ചെയ്ത് പൊതുജനങ്ങൾക്ക് മുന്നിൽ ഈ ഓഫീസായി ചമയാൻ കഴിയും.' },
    fix: { en: 'Renew the domain registration now and, if possible, set it to auto-renew for several years.', ml: 'ഡൊമെയ്ൻ രജിസ്ട്രേഷൻ ഇപ്പോൾ പുതുക്കുക, കഴിയുമെങ്കിൽ പല വർഷത്തേക്ക് ഓട്ടോ-റിന്യൂ ചെയ്യാൻ സെറ്റ് ചെയ്യുക.' },
    ref: '',
  },
  'id.www_consistency': {
    category: 'identity',
    severity: 'L',
    title: { en: 'www and non-www versions are inconsistent', ml: 'www ഉം non-www ഉം പതിപ്പുകൾ പൊരുത്തമില്ലാത്തതാണ്' },
    citizen: { en: 'Depending on whether you type "www." or not, you might get a different result than expected instead of one consistently redirecting to the other.', ml: '"www." ടൈപ്പ് ചെയ്യുന്നുണ്ടോ ഇല്ലയോ എന്നതിനെ ആശ്രയിച്ച്, ഒന്ന് സ്ഥിരമായി മറ്റൊന്നിലേക്ക് റീഡയറക്ട് ചെയ്യുന്നതിന് പകരം നിങ്ങൾക്ക് പ്രതീക്ഷിച്ചതിൽ നിന്ന് വ്യത്യസ്തമായ ഫലം ലഭിച്ചേക്കാം.' },
    fix: { en: 'Pick one canonical form and make the other redirect to it.', ml: 'ഒരു കാനോനിക്കൽ രൂപം തിരഞ്ഞെടുത്ത്, മറ്റേത് അതിലേക്ക് റീഡയറക്ട് ചെയ്യുന്നതാക്കുക.' },
    ref: '',
  },
  'id.robots': {
    category: 'identity',
    severity: 'L',
    title: { en: 'No robots.txt', ml: 'robots.txt ഇല്ല' },
    citizen: { en: 'This is a minor technical hygiene item about how search engines crawl the site; it rarely affects what you see directly.', ml: 'സൈറ്റ് സെർച്ച് എഞ്ചിനുകൾ എങ്ങനെ ക്രോൾ ചെയ്യുന്നു എന്നതിനെക്കുറിച്ചുള്ള ഒരു ചെറിയ സാങ്കേതിക ശുചിത്വ ഇനമാണിത്; ഇത് നിങ്ങൾ കാണുന്നതിനെ അപൂർവ്വമായേ നേരിട്ട് ബാധിക്കൂ.' },
    fix: { en: 'Add a robots.txt that at least allows normal crawling.', ml: 'ചുരുങ്ങിയത് സാധാരണ ക്രോളിംഗ് അനുവദിക്കുന്ന ഒരു robots.txt ചേർക്കുക.' },
    ref: '',
  },
  'id.sitemap_xml': {
    category: 'identity',
    severity: 'L',
    title: { en: 'No sitemap.xml', ml: 'sitemap.xml ഇല്ല' },
    citizen: { en: 'This helps search engines find every page on the site; without it, some pages may be harder to discover via search.', ml: 'സൈറ്റിലെ എല്ലാ പേജും കണ്ടെത്താൻ ഇത് സെർച്ച് എഞ്ചിനുകളെ സഹായിക്കുന്നു; ഇത് ഇല്ലെങ്കിൽ, ചില പേജുകൾ സെർച്ച് വഴി കണ്ടെത്തുന്നത് ബുദ്ധിമുട്ടായേക്കാം.' },
    fix: { en: 'Generate and serve a sitemap.xml, and reference it from robots.txt.', ml: 'ഒരു sitemap.xml സൃഷ്ടിച്ച് നൽകുകയും, robots.txt-ൽ നിന്ന് അതിലേക്ക് റഫർ ചെയ്യുകയും ചെയ്യുക.' },
    ref: '',
  },
  'id.soft_404': {
    category: 'identity',
    severity: 'L',
    title: { en: 'Missing pages return "200 OK" instead of a proper error', ml: 'കാണാതായ പേജുകൾ ശരിയായ പിശകിന് പകരം "200 OK" നൽകുന്നു' },
    citizen: { en: "When a page doesn't exist, the site still says everything's fine instead of telling you clearly that the page is missing, which can be confusing and hides real problems.", ml: 'ഒരു പേജ് നിലവിലില്ലാത്തപ്പോൾ, പേജ് കാണാതായെന്ന് വ്യക്തമായി പറയുന്നതിന് പകരം സൈറ്റ് എല്ലാം ശരിയാണെന്ന് പറയുന്നു, ഇത് ആശയക്കുഴപ്പമുണ്ടാക്കുകയും യഥാർത്ഥ പ്രശ്നങ്ങൾ മറയ്ക്കുകയും ചെയ്യും.' },
    fix: { en: 'Return a proper 404 status (with a helpful error page) for URLs that do not exist.', ml: 'നിലവിലില്ലാത്ത URL-കൾക്ക് ശരിയായ 404 സ്റ്റാറ്റസ് (ഉപകാരപ്രദമായ എറർ പേജോടെ) നൽകുക.' },
    ref: '',
  },
  'id.canonical': {
    category: 'identity',
    severity: 'I',
    title: { en: 'No canonical link tag', ml: 'കാനോനിക്കൽ ലിങ്ക് ടാഗ് ഇല്ല' },
    citizen: { en: 'A technical signal to search engines about which URL is the "real" one for this page is missing; it rarely affects what you see directly.', ml: 'ഈ പേജിന്റെ "യഥാർത്ഥ" URL ഏതാണെന്ന് സെർച്ച് എഞ്ചിനുകൾക്കുള്ള സാങ്കേതിക സൂചന ഇല്ല; ഇത് നിങ്ങൾ കാണുന്നതിനെ അപൂർവ്വമായേ നേരിട്ട് ബാധിക്കൂ.' },
    fix: { en: 'Add a <link rel="canonical"> to each page pointing at its preferred URL.', ml: 'ഓരോ പേജിനും അതിന്റെ ഇഷ്ടപ്പെട്ട URL ചൂണ്ടിക്കാണിക്കുന്ന ഒരു <link rel="canonical"> ചേർക്കുക.' },
    ref: '',
  },
  'id.charset_doctype': {
    category: 'identity',
    severity: 'L',
    title: { en: 'Missing UTF-8 charset or HTML5 doctype', ml: 'UTF-8 ചാർസെറ്റോ HTML5 ഡോക്ടൈപ്പോ ഇല്ല' },
    citizen: { en: 'Without a declared UTF-8 charset, Malayalam and other non-English text can sometimes render as garbled characters in some browsers.', ml: 'UTF-8 ചാർസെറ്റ് പ്രഖ്യാപിച്ചിട്ടില്ലെങ്കിൽ, ചില ബ്രൗസറുകളിൽ മലയാളവും മറ്റ് ഇംഗ്ലീഷ് അല്ലാത്ത ടെക്സ്റ്റും ചിലപ്പോൾ കുഴഞ്ഞ അക്ഷരങ്ങളായി കാണപ്പെട്ടേക്കാം.' },
    fix: { en: 'Add <!DOCTYPE html> and a UTF-8 charset declaration to every page.', ml: 'ഓരോ പേജിലും <!DOCTYPE html>, ഒരു UTF-8 ചാർസെറ്റ് പ്രഖ്യാപനം എന്നിവ ചേർക്കുക.' },
    ref: '',
  },
  'id.tech': {
    category: 'identity',
    severity: 'M',
    title: { en: 'Running old, unsupported software', ml: 'പഴയതും പിന്തുണയില്ലാത്തതുമായ സോഫ്റ്റ്‌വെയർ ഉപയോഗിക്കുന്നു' },
    citizen: { en: 'The site is built on a content-management system or platform version old enough that it likely no longer receives security updates.', ml: 'ഈ സൈറ്റ് നിർമ്മിച്ചിരിക്കുന്ന കണ്ടന്റ്-മാനേജ്മെന്റ് സിസ്റ്റം (CMS) അല്ലെങ്കിൽ പ്ലാറ്റ്ഫോം പതിപ്പ് വളരെ പഴയതായതിനാൽ, ഇനി സുരക്ഷാ അപ്ഡേറ്റുകൾ ലഭിക്കാനിടയില്ല.' },
    fix: { en: 'Upgrade the CMS/platform to a currently-supported version.', ml: 'CMS/പ്ലാറ്റ്ഫോം നിലവിൽ പിന്തുണയുള്ള ഒരു പതിപ്പിലേക്ക് അപ്ഗ്രേഡ് ചെയ്യുക.' },
    ref: '',
  },
  'id.third_party': {
    category: 'identity',
    severity: 'I',
    title: { en: 'Loads third-party trackers', ml: 'മൂന്നാം-കക്ഷി ട്രാക്കറുകൾ ലോഡ് ചെയ്യുന്നു' },
    citizen: { en: 'This page loads scripts from outside companies (analytics, social-media widgets) that can track your visit, shown here for transparency rather than as a pass/fail problem.', ml: 'നിങ്ങളുടെ സന്ദർശനം ട്രാക്ക് ചെയ്യാൻ കഴിയുന്ന പുറത്തുള്ള കമ്പനികളിൽ നിന്നുള്ള സ്ക്രിപ്റ്റുകൾ (അനലിറ്റിക്സ്, സോഷ്യൽ-മീഡിയ വിജറ്റുകൾ) ഈ പേജ് ലോഡ് ചെയ്യുന്നു, ഇത് ഒരു പാസ്/ഫെയിൽ പ്രശ്നമായിട്ടല്ല, സുതാര്യതയ്ക്കായി കാണിക്കുന്നതാണ്.' },
    fix: { en: 'Consider whether each third-party script is necessary, and disclose tracking in the Privacy Policy if kept.', ml: 'ഓരോ മൂന്നാം-കക്ഷി സ്ക്രിപ്റ്റും ആവശ്യമാണോ എന്ന് പരിഗണിക്കുക, നിലനിർത്തുകയാണെങ്കിൽ Privacy Policy-യിൽ ട്രാക്കിംഗ് വെളിപ്പെടുത്തുക.' },
    ref: '',
  },
};
